### ISSUE TITLE
Проверить цены за услуги

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#100]
### С чем связан запрос на фичу?

Важно убедиться что цены за услуги на сайте динамические - тянутся из внешки (S3)

### Расскажите как вы это себе видите

- [ ] цены не статичны

**Comment by kirill-ivanovvv** [comment]
@Nelfimov сейчас все информация о сервисах, в тч цена приходит после graphql-запроса по этому адресу:
https://github.com/torin-asakura/shdvor/blob/6ad0271650946f0129680913bf066b3049272049/globals/data/src/apollo/apollo.constants.ts#L2

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
мне только цену запрашивать с S3 - остальное оставить с WP, или все данные менять на S3?

можешь дать значения `API_URL` для S3 хранилища? я посмотрю как приходящие данные вообще выглядят. S3 у нас используется в `@prices/service-entrypoint`
```ts
export const API_URL = process.env.API_URL
```

**Comment by Nelfimov** [comment]
У тебя два пути:
1. как ты предлагаешь - запросить цены с `API_URL` и их там обработать. Можешь оценить по `prices` сложно ли это
2. запрашивать из бакета - вышлю файл-результат выполнения `prices` в телеге

**Comment by TorinAsakura** [comment]
статус?

**Comment by kirill-ivanovvv** [comment]
> статус?

в процессе

**Comment by TorinAsakura** [comment]
> > статус?
> 
> в процессе

тогда почему у задачи нет статуса?

**Comment by kirill-ivanovvv** [comment]
> У тебя два пути:
> 
> 1. как ты предлагаешь - запросить цены с `API_URL` и их там обработать. Можешь оценить по `prices` сложно ли это
> 2. запрашивать из бакета - вышлю файл-результат выполнения `prices` в телеге

немного не понял тебя

с xml рабоать неудобно.
даже если в json конвертировать всеравно придется разбирать строки, потомучто ни категоний, ни размера колес - нету.
нужно будет разобрать это -> сразувнить с wordpress-данными и заменить prices. выглядит трудоемко

судя по `@prices` в приходящем объекте есть поля group и group-id, можно айди связать с категориями и дальше фильтровать будет удобнее
может быть есть поля `категория автомобиля` и `радуис`, тогда вообще будет очень удобно это сделать. нужно посмотреть

для того, чтобы посмотрреть, мне нужнен вот этот ключ, у меня его нету. `prices` тестировали в проде:
```ts
export const API_URL = process.env.API_URL
```

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус

#### Дальнейшие планы
- запросить данные с `КАССОВОГО СЕРВИСА` по аналогии с `@prices` (bootstrap)
- сделать этот запрос с сервера, закешировать данные
- с клиента запрашивать закешированные данные нашего, серверного роута
- заменить цены, приходящие с WP - на цены, приходящие с `КАССОВОГО СЕРВИСА`

#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/fix/prices

**Comment by TorinAsakura** [comment]
> `API_URL` - https://api.aqsi.ru/pub/v2
> 
> `API_KEY` кину в ЛС

полагаю можно было передать через секреты…

**Comment by kirill-ivanovvv** [comment]
@Nelfimov некст же должен каждый фетч-запрос кешировать?
сейчас данные запрашиваю с сервера у трех страниц и передаю через прос на клиент
на клиенте меняю WP-ЦЕНЫ на AQSI-ЦЕНЫ, все остальные данные не трогаю

до WP-ДАННЫХ получается добраться только на клиенте, потомучто мы их запрашиваем через useSuspenseQuery - а он клиентский.

ключ назвал вот так:
`AQSI_API_KEY`

**Comment by Nelfimov** [comment]
> @Nelfimov некст же должен каждый фетч-запрос кешировать?

Можешь сделать через ревалидацию данных аналогично логике как мы сделали для обычных страниц ISR. 

> сейчас данные запрашиваю с сервера у трех страниц и передаю через прос на клиент
> 
> на клиенте меняю WP-ЦЕНЫ на AQSI-ЦЕНЫ, все остальные данные не трогаю
> 
> 
> 
> до WP-ДАННЫХ получается добраться только на клиенте, потомучто мы их запрашиваем через useSuspenseQuery - а он клиентский.

Если уходим от WP по ценам то это нас уже не касается, нет?

> ключ назвал вот так:
> 
> `AQSI_API_KEY`

Проверь чтобы нейминг был как в prices

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- написал логику для запроса с локального роута
- рефакторинг
- интерфейсы
#### Дальнейшие планы
- жду результатов ревью
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/fix/prices
