### ISSUE TITLE
Ошибки `seo-metadata` 

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#101]
### Описание бага

`yandex-webmaster` сообщает, что `title` в `metadata` - пустой

### Воспроизведение

- в проде `title` в `head` отображается корректно
- не все запросы приходят:
![image](https://github.com/user-attachments/assets/234461ff-2597-4f2a-92b5-ddf29eaf6aa6)

### Ожидаемое поведение

- ошибка с недошедшими пакетами, о которых упоминаю выше
- все пакеты должны приходить

### Материалы

![image](https://github.com/user-attachments/assets/666b8924-94ab-4c9a-803b-6b20ba9ae62d)

### Данные окружения

Version 129.0.6668.70 (Official Build) Arch Linux (64-bit)

**Comment by kirill-ivanovvv** [comment]
- сейчас обновляю страницу - только один запрос не приходит, приложил в конце комментария
- все запросы яндекса работают корректно
- все `seo-скрипты` у нас настраиваются в `googletagmanager` - он написан в компоненте `Gtag`. компонент работает корректно.

@Nelfimov
- это может быть ошибка у сервисов `google`?
- это может быть ошибка у сервисов `yandex`?

<details>
<summary>failed request url</summary>

`https://td.doubleclick.net/td/ga/rul?tid=G-1KRXMM6BP7&gacid=591351459.1722837765&gtm=45je49n0v887114036za200&dma=0&gcd=13l3l3l3l1l1&npa=0&pscdl=noapi&aip=1&fledge=1&frm=0&tag_exp=101671035~101747727&z=335119113`

</details>

<details>
<summary>network screenshot</summary>

![image](https://github.com/user-attachments/assets/002504dc-7b65-438c-be7b-6c35280e82a1)

</details>

**Comment by Nelfimov** [comment]
@TorinAsakura можешь дать доступ Кириллу к вебмастеру? Иначе работа вслепую

**Comment by kirill-ivanovvv** [comment]
@Nelfimov @TorinAsakura

1. проверил, какой приходит `html` с выключенным `js` - `title` в `head` есть, все ок
2. проверил сайт на [googlepagespeedtest](https://pagespeed.web.dev/analysis/https-shdvor-pro/laoimk0r0c?form_factor=desktop) - все ок

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/cd806299-4188-4ec0-b6c8-4c3a94575cc8)

</details>

3. нашел еще один сервис для проверки - [`pagesmeter`](https://www.pagesmeter.com/tools/seo-checker/?url=https%3A%2F%2Fshdvor.pro%2F&crawlType=Standard) - показал 100% на `Meta specifications`:

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/3cc36538-d7f6-44f3-8a7f-c807d2647591)

</details>

5. в тгбота сайт закинул, вернул корректное preview

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/8c5dcaeb-2688-46c3-98ae-aeac4113c8ae)

</details>

6. проверил консоль `webmaster` на сайте - он подключен, работает

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/ba6594f7-4918-47c7-a891-4b7c2634a0d4)

</details>

<details>
<summary>были такие ошибки, но сейчас нет:</summary>

- при первичной загрузке страницы (через режим инкогнито) - `googletagmanager` загружает одни скрипты, а при всех последующих загрузках - другие скрипты.
- при загрузке первичных скриптов - в `network` вкладке `devtools` были непришедшие запросы, в том числе от `yandex`
- при вторичной был и остается один непришедший запрос `td.doubleclick.net`

</details>

**Comment by TorinAsakura** [comment]
Resolved cause https://github.com/torin-asakura/shdvor/issues/101#issuecomment-2376430308
