### ISSUE TITLE
Оповещение клиента после подтверждения записи

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#105]
### С чем связан запрос на фичу?

Необходимо дополнить функционал `booking-telegram-bot`.

### Расскажите как вы это себе видите

Бот должен оповещать клиента после того, как запись подтверждена со стороны шиномонтажки:

1. `booking-telegram-bot` добавляет запись в таблицу `appointment`
2. оператору приходит оповещение о новой неподтвержненной записи
3.1 оператор подтверждает запись
3.2 оператор отклоняет запись
4. клиенту приходит оповещение о результате подтверждения (согласованно или отклоненно)

этот функционал будет удобнее добавить после основного функционала `бота для оператора`

**Comment by TorinAsakura** [comment]
задачу оформи пожалуйста надлежащим образом

**Comment by kirill-ivanovvv** [comment]
задача включена в https://github.com/torin-asakura/shdvor/issues/83
