### ISSUE TITLE
Добавить `rest-api-endpoint` для записи с сайта

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#106]
### С чем связан запрос на фичу?

На текущей версии сайта есть форма - она, насколько я понимаю, не функционирует.
![image](https://github.com/user-attachments/assets/f6cc6160-746a-45f1-b6f4-ca0a4dfdc395)

### Расскажите как вы это себе видите

Нужно проверить и подбить функционал формы с `booking-telegram-bot` - они несут общую функцию
- [ ] запись данных в таблицу
- [ ] оповещение оператора (для подтверждения)

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
1. я правильно понимаю, что на `@site` нужно добавить `api-endpoint`. данные с формы приходят на него, а он их перебрасывает на `localhost:ПОРТ-БОТА`
2. сейчас бот не добавлен в `docker-compose`, соотвтетственно порта нету. 
3. `ПОРТ-БОТА` просто зашить в константу рядом с `api-endpoint`?
4. ну и соотвтетственно, если мы в функционал `booking-telegram-bot` добавляем доп. функции с рест-апи, то текущее название не подходит? `booking-service` будет нормально?

**Comment by Nelfimov** [comment]
У тебя есть бот который записывает данные в БД. В боте надо добавить REST эндпоинт для создания записи. Сайт будет отправлять запросы туда.

**Comment by kirill-ivanovvv** [comment]
> У тебя есть бот который записывает данные в БД. В боте надо добавить REST эндпоинт для создания записи. Сайт будет отправлять запросы туда.

я просто не могу сообразить на какой адрес с клиента отправлять данные. если у нас доменное имя привязанно к определенному порту, а сервис будет висеть на другом порту, то по доменному имени отправить не получится.

**Comment by kirill-ivanovvv** [comment]
> @Nelfimov
> 
> 1. я правильно понимаю, что на `@site` нужно добавить `api-endpoint`. данные с формы приходят на него, а он их перебрасывает на `localhost:ПОРТ-БОТА`
> 2. сейчас бот не добавлен в `docker-compose`, соотвтетственно порта нету.
> 3. `ПОРТ-БОТА` просто зашить в константу рядом с `api-endpoint`?
> 4. ну и соотвтетственно, если мы в функционал `booking-telegram-bot` добавляем доп. функции с рест-апи, то текущее название не подходит? `booking-service` будет нормально?



> > У тебя есть бот который записывает данные в БД. В боте надо добавить REST эндпоинт для создания записи. Сайт будет отправлять запросы туда.
> 
> я просто не могу сообразить на какой адрес с клиента отправлять данные. если у нас доменное имя привязанно к определенному порту, а сервис будет висеть на другом порту, то по доменному имени отправить не получится.

@Nelfimov я тогда вот так делаю^^^ или можно както адрес `booking-telegram-bot` получить с клиента?

**Comment by Nelfimov** [comment]
у тебя два варианта:
1. делаешь `api` эндпоинт на `site`. На него отправляются данные с формы. Эндпоинт в свою очередь отправляет данные на `booking-bot` по внутренней сети кубера - мне меньше работы. Адрес бота зашиваешь в переменные окружения
2. отправляешь данные из формы сразу на бота через POST запрос. Тогда мне придется открывать доступ к боту для внешки. Адрес бота так же зашиваешь в переменные окружения

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- сделал миграцию для сайта. немного отличаются поля
- создал инфраструкуру для api
- fetch с клиента на api-endpoint
- fetch с api-endpoint на service-api-endpoint
- все интерфейсы в сервисе, в т.ч запись
#### Дальнейшие планы
- нужно протестировать и закрыть ошибки чеков - этим не занимался
- сильно тормозит при запуске двух сервисов. 
- разрабатывал 2 куска отдельно, тестировал - работает, в бд пишет. хочу сделать финальный тест - совместный.
#### Актуальная ветка
- не самые свежие изменения, завтра решу конфликты
- https://github.com/torin-asakura/shdvor/tree/feat/rest-api-endpoint
