### ISSUE TITLE
Паблиш бота

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#107]
### Описание бага

Приложение букинг бота не билдится. Последний удачный паблиш - 08.10.

### Воспроизведение

1. Мержим в мастер
2. Смотри экшен `Publish`

### Ожидаемое поведение

Паблиш прошел успешно.

### Материалы

https://github.com/torin-asakura/shdvor/actions/runs/11462384317/job/31893643226#step:9:98

### Данные окружения

GitHub Action

**Comment by Nelfimov** [comment]
Билд прошел, однако в логах ошибка

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/c07d6ef4-afd5-44e6-adb9-5167bde9660b">

**Comment by kirill-ivanovvv** [comment]
> Билд прошел, однако в логах ошибка
> 
> <img alt="image" width="1022" src="https://private-user-images.githubusercontent.com/44067768/379248414-c07d6ef4-afd5-44e6-adb9-5167bde9660b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODQyOTksIm5iZiI6MTcyOTY4Mzk5OSwicGF0aCI6Ii80NDA2Nzc2OC8zNzkyNDg0MTQtYzA3ZDZlZjQtYWZkNS00NGU2LWFkYjktNTE2N2JkZTk2NjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDExNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZGM0ZmFlM2VmNDg2YzA0OTdmMjIwNTE1Y2QwOWFkNGI5ZDkyMzYxNDEyMDY1ZDNkNmYwNjk3NTdiMjU3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9kgUdKRp4iTE2Gv-qtWa5bx0iEUL3lsRXKeHGvbAd3U">

а на хостинг только сбилженная часть улетает или все прилжение целиком, а затем собирается на хосте?

**Comment by Nelfimov** [comment]
билдится образ в гх экшене. Образ разворачивается в кубере

`yarn image pack...`

**Comment by kirill-ivanovvv** [comment]
@Nelfimov щас тоже ошибка? бот не откликается

**Comment by Nelfimov** [comment]
Ошибка переводов прошла. 

Теперь мне нужен от тебя токен для бота

**Comment by kirill-ivanovvv** [comment]
> Ошибка переводов прошла.
> 
> Теперь мне нужен от тебя токен для бота

BOOKING_BOT_API_HASH
1456d21e179cc0d3165bd3f65424db87

BOOKING_BOT_API_ID
27275852

BOOKING_BOT_BOT_TOKEN
6451409399:AAENpt4tPx8m55kl-1QEQyEnAnvY4gaJ7rc

**Comment by Nelfimov** [comment]
Забирай

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/23b7705d-16f8-4b9e-beb2-1e78b060460d">

**Comment by kirill-ivanovvv** [comment]
> Забирай
> 
> <img alt="image" width="1014" src="https://private-user-images.githubusercontent.com/44067768/379405648-23b7705d-16f8-4b9e-beb2-1e78b060460d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDQ4MjMsIm5iZiI6MTcyOTc0NDUyMywicGF0aCI6Ii80NDA2Nzc2OC8zNzk0MDU2NDgtMjNiNzcwNWQtMTZmOC00YjllLWJlYjItMWU3OGIwNjA0NjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA0MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1Y2M2ZWNjYWEwNDZlZGIzOWUyYzFhNGZkOTI1YjUzM2Q1ZTg2NWU4ZTZkOGM3ODM1OGY0ZTY1MTkwMDQ4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rwQsqMqxUkMEAx3xYfe-uK5XFW3-A0sQL667EZozrJs">

🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏
