### ISSUE TITLE
Добавить телеграм-аккаунт в секцию `контакты`

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#112]
### С чем связан запрос на фичу?

Добавить способ связи

### Расскажите как вы это себе видите

- [x] - добавить ссылку - @Nelfimov как делать, другие ссылки приходят с WP
- [x] - добавить иконку (SVG) - провести к ней ссылку
- [x] - свести все это в компоненте `social-links`

**Comment by Nelfimov** [comment]
дай свою почту

**Comment by kirill-ivanovvv** [comment]
> дай свою почту

kirill-ivanovvvvvvv@yandex.ru

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- поправил верстку
- провел пропсы
- расширил интерфейсы
- 
#### Дальнейшие планы
- добавить в ВП запись
- проверить

#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/telegram-account-link

**Comment by Nelfimov** [comment]
> > дай свою почту
> 
> [kirill-ivanovvvvvvv@yandex.ru](mailto:kirill-ivanovvvvvvv@yandex.ru)

отправил инвайт
