### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shdvor#12]
### Проблема

Слайдер работает криво: 

- При слайде меняется стейт абсолютно всех слайдов, а не только активного
- Искажается изображение внутри слайда при изменении шейпа
- Иногда багуется отображение доп. информации на слайде

### Материалы

https://user-images.githubusercontent.com/62806448/177360081-7e6bbee2-dbe0-46fa-a9be-a1d28b826dc8.mov

### Задача

Использовать другой инструмент для слайдера или найти способ адекватно адаптировать splide под наши требования

**Comment by TFK70** [comment]
@carminio кинул пок слайдера который решает твои проблемы, но

1. Ты неправильно реализовал мобильную версию слайдера. Так адаптируется он через жопу - то делать нужно как на [misik](https://github.com/torin-asakura/misik/blob/master/landing/fragments/landing-work-directions/src/carousel/carousel.component.tsx), то есть не заставлять его адаптироваться, а сделать разные версии слайдеров: отдельно для мобилки и для десктопа, и по брейкпоинтам просто отдавать разные компоненты
2. Я так и не понял почему ты решил не брать свайпер из `@atls-ui-parts`. Ты спокойно мог реализовать то же самое и со свайпером из атлс, заодно не пришлось бы лишний раз прописывать [это](https://github.com/torin-asakura/shdvor/pull/27/commits/3ff62d458948d9e4fcfcb882d9486f101bad6983#diff-c6ac774ecf796783f66154b03d9b6ae9b8f6ac24d95bbc9abca81a7f3e4e4fc4R25), так как эта проблема уже решена в атлс либе

**Comment by carminio** [comment]
## Проблема с расположением фотографий в слайде

@TFK70 

### Описание

Для сравнения фотографий использую либу [ReactCompareImage](https://www.npmjs.com/package/react-compare-image), есть одна проблема, это корректно отображать картинки в активном слайде на десктопе и мобилках, оно почему-то криво масштабируется.

### Шаги воспроизведения

1. ветка fix/slider
2. yarn && yarn workspace @site/app dev
3. На главной странице спускаемся к слайдеру 
4. Видим кривое расположение картинок в активном слайде

### Материалы

Вот так это выглядит сейчас

<details>

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/35490768/195568922-983898d4-4b98-46cd-94ed-2fb2792c293c.png">

</details>

[ReactCompareImage](https://github.com/torin-asakura/shdvor/blob/fix/slider/ui/slider/src/slide/slide.component.tsx#L46-L69) в коде

### Вопрос
Как корректно расположить фотки в активном слайде
