### ISSUE TITLE
Перенести компоненты на новый hyperion

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#121]
### С чем связан запрос на фичу?

необходимо проапгрейдить версию пакета до последней

### Расскажите как вы это себе видите

- [ ] - изменить версию пакета
- [ ] - проверить верстку

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- обновил версии в ui
- прописал недостающие пакеты ошибки в packageExtensions
- покачто все компоненты закрыл заглушками. 
#### Дальнейшие планы
- страницу отрендерить не получается, вырезал все фрагменты, оставил только footer. 
- в footer была неудобная для отладки верстка - слишком большое полотно, поделил на parts
- буду отлаживать, выяснять какой компонент вызывает эту ошибку

- хочу отрендерить страницу, затем пройтись по каждому компоненту и подтянуть его стиль, адаптировать под новую библиотеку.

```log
⨯ TypeError: Cannot read properties of undefined (reading '0')
    at Array.map (<anonymous>)
digest: "2246390963"
 GET / 500 in 42288ms
```
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
- я же правильно понимаю, что глобально брейкпонты, как в `styled-components` назначить не получится?
- изучаю документацию, и тему responsive вижу только в `@vanilla-extract/sprinkles`
- мне нужно переопределить responsive-компоненты, добавив к ним брейкпониты - верно?
- в гинеперионе мы используем `rainbow-sprinkles` - в его документации тоже есть тема responsive, аналогичная `@vanilla-extract/sprinkles` - поэтому буду использовать его - https://github.com/wayfair/rainbow-sprinkles?tab=readme-ov-file#setup

**Comment by Nelfimov** [comment]
@Amiditin ответь плиз

**Comment by Amiditin** [comment]
> * я же правильно понимаю, что глобально брейкпонты, как в `styled-components` назначить не получится?

@kirill-ivanovvv можно в тему добавить `breakpoints` и от них отталкиваться при написании `@media`

> изучаю документацию, и тему responsive вижу только в @vanilla-extract/sprinkles
мне нужно переопределить responsive-компоненты, добавив к ним брейкпониты - верно?

Да

> в гинеперионе мы используем rainbow-sprinkles - в его документации тоже есть тема responsive, аналогичная @vanilla-extract/sprinkles - поэтому буду использовать его - https://github.com/wayfair/rainbow-sprinkles?tab=readme-ov-file#setup

Да, используем `rainbow-sprinkles`, по идее в доке рабочий вариант написан

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- разбирался с библиотекой
- создал тему, подключил
- создал респонсив-варианты лейаут компонентов
- разбил весь бам на подзадачи, висят в ишью
#### Дальнейшие планы
- сейчас перебиваю футер, хочу убедиться в том, что все будет рабоать. перебиваю респонсив-пропсы. с ванилла-екстракт немного по-другому работает
- следом буду перебивать все оставшиеся фрагменты
- потом страницы
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- в основном, занимался генераторами, их закончил - https://github.com/torin-asakura/shdvor/issues/147
- в текущей ветке переверстывал фрагменты.
#### Дальнейшие планы
- доделывать верстку фрагментов буду в этой таске - https://github.com/torin-asakura/shdvor/issues/146
- сливать изменения буду в основную ветку, при помощи ПР - https://github.com/torin-asakura/shdvor/tree/feat/regenerate-figma
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by kirill-ivanovvv** [comment]
разделил задачу на несколько:
- https://github.com/torin-asakura/shdvor/issues/148
- https://github.com/torin-asakura/shdvor/issues/147
- https://github.com/torin-asakura/shdvor/issues/146
