### ISSUE TITLE
Бамп бандла yarn

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#122]
### С чем связан запрос на фичу?

Вышла новая версия

### Расскажите как вы это себе видите

скопировать вставить
https://github.com/atls/raijin/tree/master/yarn/cli/dist

### Приложите пример реализаций

новый бандл ярна:
- работает на 22 ноде и выше
- нужен @atls/code-runtime последней версии
- нужен в корне проекта установленный последний eslint

лежит тут:

https://github.com/atls/raijin/tree/master/yarn/cli/dist

Обновляем во всех проектах кроме delta-doc

Ошибки/баги заводим таски и вешаем на меня:
https://github.com/atls/raijin/issues

**Comment by kirill-ivanovvv** [comment]
@Nelfimov просит .cjs расширение:

```console
Error: Cannot find module '/home/operator/work/atls_shdvor/.yarn/releases/yarn.cjs'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

- code-reuntime - обновил
- eslint - обновил

- https://github.com/torin-asakura/shdvor/tree/feat/yarn-bump

**Comment by Nelfimov** [comment]
А yarnPath ты обновил?

**Comment by Nelfimov** [comment]
Обновил бандл, фикс в ПРе выше. Закоммитил в твою ветку обновление
