### ISSUE TITLE
Изменить таблицу товаров 2gis

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#124]
### С чем связан запрос на фичу?

обновление таблицы

### Расскажите как вы это себе видите

изучить:
https://stories.2gis.ru/vitrina
https://dostavili.2gis.ru/public/1120/goods/

обновленная таблица:
[41d9bc70-aab3-447a-9cce-92168a7a204f.xlsx](https://github.com/user-attachments/files/17841981/41d9bc70-aab3-447a-9cce-92168a7a204f.xlsx)

**Comment by kirill-ivanovvv** [comment]
@TorinAsakura, нужен доступ к ЛК, чтобы обновить витрину
https://sberbusiness.live/publications/onlain-vitriny-v-2gis-prevrashchaiut-prokhozhikh-v-pokupatelei-nastroite-vitrinu-za-5-shagov
![image](https://github.com/user-attachments/assets/61bb313e-eda5-4a38-88f5-51e3c10e437c)

**Comment by TorinAsakura** [comment]
> @TorinAsakura, нужен доступ к ЛК, чтобы обновить витрину https://sberbusiness.live/publications/onlain-vitriny-v-2gis-prevrashchaiut-prokhozhikh-v-pokupatelei-nastroite-vitrinu-za-5-shagov ![image](https://private-user-images.githubusercontent.com/70315473/388535019-61bb313e-eda5-4a38-88f5-51e3c10e437c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDQ4MzMsIm5iZiI6MTczMjIwNDUzMywicGF0aCI6Ii83MDMxNTQ3My8zODg1MzUwMTktNjFiYjMxM2UtZWRhNS00YTM4LTg4ZjUtNTFlM2MxMGU0MzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE1NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODliNzU2YTg0NDlhMWRmMDlmODc1NTBhMTAyNzQzNGVkZmQ5NDM5NzE1YzE0MDJkNDI2YzdiOWI5MjUwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SUswlki-qqVqE5yiuF-YEWhxnSS9HW3J0dxUoObL21g)

какую ещё витрину ты собрался обновлять? Нам нужен такой же генератор фида как и для яндекса. О чём ты вообще?

**Comment by TorinAsakura** [comment]
> я не понимаю
> 
> > > @TorinAsakura, нужен доступ к ЛК, чтобы обновить витрину https://sberbusiness.live/publications/onlain-vitriny-v-2gis-prevrashchaiut-prokhozhikh-v-pokupatelei-nastroite-vitrinu-za-5-shagov ![image](https://private-user-images.githubusercontent.com/70315473/388535019-61bb313e-eda5-4a38-88f5-51e3c10e437c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDQ4MzMsIm5iZiI6MTczMjIwNDUzMywicGF0aCI6Ii83MDMxNTQ3My8zODg1MzUwMTktNjFiYjMxM2UtZWRhNS00YTM4LTg4ZjUtNTFlM2MxMGU0MzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE1NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODliNzU2YTg0NDlhMWRmMDlmODc1NTBhMTAyNzQzNGVkZmQ5NDM5NzE1YzE0MDJkNDI2YzdiOWI5MjUwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SUswlki-qqVqE5yiuF-YEWhxnSS9HW3J0dxUoObL21g)
> > 
> > 
> > какую ещё витрину ты собрался обновлять? Нам нужен такой же генератор фида как и для яндекса. О чём ты вообще?
> 
> * я думал что нужно обновить цены в 2гисе
> 
> у яндекса мы:
> 
> 1. запрашиваем данные с aqsi
> 2. форматируем их в xml
> 3. отправляем xml на s3-бакета
> 4. как я понимею яндекс запрашивает с s3-бакета
> 
> мне нужно по тому формату, что ты скинул отформатировать приходящие с aqsi данные и сделать аналогичто с xml для яндекса? ИЛИ мне нужно создать роут в сервисе `@prices`, который будет отправлять тот файл, что ты скинул? ты говорил что он новый

И так ещё раз. Мы делаем такой же фид для 2гиса как и для яндекса, вся процедура точно такая же. Наша задача - синхронизация цен с кассой. Что не ясно-то?

**Comment by kirill-ivanovvv** [comment]
> > я не понимаю
> > > > @TorinAsakura, нужен доступ к ЛК, чтобы обновить витрину https://sberbusiness.live/publications/onlain-vitriny-v-2gis-prevrashchaiut-prokhozhikh-v-pokupatelei-nastroite-vitrinu-za-5-shagov ![image](https://private-user-images.githubusercontent.com/70315473/388535019-61bb313e-eda5-4a38-88f5-51e3c10e437c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDQ4MzMsIm5iZiI6MTczMjIwNDUzMywicGF0aCI6Ii83MDMxNTQ3My8zODg1MzUwMTktNjFiYjMxM2UtZWRhNS00YTM4LTg4ZjUtNTFlM2MxMGU0MzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE1NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODliNzU2YTg0NDlhMWRmMDlmODc1NTBhMTAyNzQzNGVkZmQ5NDM5NzE1YzE0MDJkNDI2YzdiOWI5MjUwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SUswlki-qqVqE5yiuF-YEWhxnSS9HW3J0dxUoObL21g)
> > > 
> > > 
> > > какую ещё витрину ты собрался обновлять? Нам нужен такой же генератор фида как и для яндекса. О чём ты вообще?
> > 
> > 
> > 
> > * я думал что нужно обновить цены в 2гисе
> > 
> > у яндекса мы:
> > 
> > 1. запрашиваем данные с aqsi
> > 2. форматируем их в xml
> > 3. отправляем xml на s3-бакета
> > 4. как я понимею яндекс запрашивает с s3-бакета
> > 
> > мне нужно по тому формату, что ты скинул отформатировать приходящие с aqsi данные и сделать аналогичто с xml для яндекса? ИЛИ мне нужно создать роут в сервисе `@prices`, который будет отправлять тот файл, что ты скинул? ты говорил что он новый
> 
> И так ещё раз. Мы делаем такой же фид для 2гиса как и для яндекса, вся процедура точно такая же. Наша задача - синхронизация цен с кассой. Что не ясно-то?

понял. тогда форматирую входящие данные по формату того файла, что ты скинул и помещаю также в с3-бакет

**Comment by kirill-ivanovvv** [comment]
@Nelfimov а лог так и должен выглядеть?
![image](https://github.com/user-attachments/assets/c9c25c7f-0d76-456b-80cb-c74e39691b22)

**Comment by Nelfimov** [comment]
это вывод чего?

**Comment by kirill-ivanovvv** [comment]
> это вывод чего?

просто массив с вложенными объектами

**Comment by Nelfimov** [comment]
ну тяжело ответить не зная как ты выводишь лог.

В новом бандле есть характерная ему обводка для сообщений

**Comment by kirill-ivanovvv** [comment]
> ну тяжело ответить не зная как ты выводишь лог.
> 
> В новом бандле есть характерная ему обводка для сообщений

- в `console.log` закинул массив, выводит каждый объект этого массива построчно - как в [скриншоте](https://github.com/torin-asakura/shdvor/issues/124#issuecomment-2498185149) 
- попробовал через `@atls/logger`, есть ошибка:
  - строку выводит в штатном режиме
  - объект типа `Array<{id: string, name: string}>` не выводит, возвращает ошибку: 
```ts

  ERROR Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D for the full message or
       use the non-minified dev environment for full errors and additional helpful warnings.

 file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:11952

 - oe (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:11952)
 - el (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:13789)
 - nd (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:15062)
 -  (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:17489)
 - bo (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:278:28449)
 - hp (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:282:9019)
 - OI (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:282:991)
 - DB (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:282:919)
 - Lp (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:282:769)
 - kI (file:///home/operator/work/atls_shdvor/.yarn/releases/yarn-remote.mjs:280:12672)
```

**Comment by Nelfimov** [comment]
попробуй `console.dir` либо `@monstrs/logger`

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- занимаюсь перебором входящих данных - в процессе
- рефактор
#### Дальнейшие планы
- связать вложенные позиции с категориями при помощи `group-id`
- сформировать xml по аналогии с уже готовым функционалом
- вынести общий функционал в getters, преимущественно
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/2gis-feed

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- функционал готов, работает
- проверил итоговый xml, все сходится
- на бакет не могу сделать тестовую отправку, нету ключей. должно рабоать, в эту часть кода не вносил изменений.
#### Дальнейшие планы
- не успеваю поделить на модули
- не до конца разобрался с domain-module. бота делали без него, только с infrastructure-module и application-module
- разобраться
- сделать
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/2gis-feed

**Comment by Nelfimov** [comment]
> * не до конца разобрался с domain-module. бота делали без него, только с infrastructure-module и application-module

Пиши на клине, как бота. Маппинги цен под каждый сервис (яндекс, 2гис) - отдельные юзкейсы

**Comment by kirill-ivanovvv** [comment]
@Nelfimov у меня ключей нету, чтобы бакет проверить

```ts
export const PRICES_REQUIRED_ENVS = [
  'API_KEY',
  'FILES_STORAGE_HOST',
  'FILES_STORAGE_REGION',
  'YC_SA_KEY_ID',
  'YC_SA_SECRET_KEY',
]
```

**Comment by Nelfimov** [comment]
> @Nelfimov у меня ключей нету, чтобы бакет проверить
> 
> ```ts
> export const PRICES_REQUIRED_ENVS = [
>   'API_KEY',
>   'FILES_STORAGE_HOST',
>   'FILES_STORAGE_REGION',
>   'YC_SA_KEY_ID',
>   'YC_SA_SECRET_KEY',
> ]
> ```

Локально файл создай для проверки. А в отправлении убедись что не конфликта имен файлов.

**Comment by kirill-ivanovvv** [comment]
> > @Nelfimov у меня ключей нету, чтобы бакет проверить
> > 
> > ```ts
> > export const PRICES_REQUIRED_ENVS = [
> >   'API_KEY',
> >   'FILES_STORAGE_HOST',
> >   'FILES_STORAGE_REGION',
> >   'YC_SA_KEY_ID',
> >   'YC_SA_SECRET_KEY',
> > ]
> > ```
> 
> Локально файл создай для проверки. А в отправлении убедись что не конфликта имен файлов.

локально проверял 
имена разные, в пр указал
