### ISSUE TITLE
Рефактор, гиперион-бамп, верстка pages & fragments

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#146]
### С чем связан запрос на фичу?

Новая библиотека не съедает массив вариантов для респонсов. В пропс нужно передавать объект

### Расскажите как вы это себе видите

https://github.com/torin-asakura/shdvor/pull/145/commits/c8a4f5a8035ec7002fe7045f908acba4ab296a12

- внес правки в тему, подключил её в рут-лейаут
- добавил компонент RexponseBox в Layout
- добавил mapper для респонсив компонентов

---

- [x] responsive layout variants
- [x] responsive text variants
- [ ] check buttons 
   - [ ] size namings
   - [ ] variant namings

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- добил mapper
- добил его types
- вернул исходную верстку (с массивами)
- сверил верску, при выключенном js (есть ошибки в хуках) - ошибок в контейнерах нет, страница собирается
- responsive arrays проверял изолированно
#### Дальнейшие планы
- кажется еще text тоже имеет responsive styles. перепроверю, если да, то сделаю по аналогии
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by Nelfimov** [comment]
когда отдашь на ревью?

**Comment by kirill-ivanovvv** [comment]
> когда отдашь на ревью?

когда закончу верстку buttons нужно будет проверить наименования variants
на этом, вроде, в глобальной верстке - все, переключусь на компоненты

**Comment by kirill-ivanovvv** [comment]
перенес задачи в https://github.com/torin-asakura/shdvor/issues/163
