### ISSUE TITLE
Рефактор, гиперион-бамп, генерация новых `theme`, `buttons`, `icons`

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#147]
### С чем связан запрос на фичу?

Новая библиотека не принимает глубоко вложенный объект

### Расскажите как вы это себе видите

- [x] - перегенерировать
  - [x] - buttons
  - [x] - icons
  - [x] - theme

- в детали не вдавался, но новая либа не принимает объект из темы с глубоким вложением, типа - https://github.com/torin-asakura/shdvor/blob/master/ui/theme/src/theme/colors.ts

- должно быть чтото подобное - https://github.com/atls/hyperion/blob/master/ui-parts/theme/src/theme/colors.ts

### Приложите пример реализаций

https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0-1&node-type=canvas&t=scoA1oaZWAJz7DnG-0

**Comment by kirill-ivanovvv** [comment]
При генерации темы есть баг - https://github.com/atls/figma/issues/42

**Comment by Amiditin** [comment]
> При генерации темы есть баг - [atls/figma#42](https://github.com/atls/figma/issues/42)

Новая версия [генератора](https://www.npmjs.com/package/@atls/figma-theme-cli), можешь проверять

**Comment by kirill-ivanovvv** [comment]
все компоненты перегенерировал, актуальные изменения находятся в https://github.com/torin-asakura/shdvor/tree/feat/regenerate-figma

**Comment by Nelfimov** [comment]
@kirill-ivanovvv задача выполнена?

**Comment by kirill-ivanovvv** [comment]
> @kirill-ivanovvv задача выполнена?

при генерации buttons получилось только appearance, сейчас пишу верстку

**Comment by kirill-ivanovvv** [comment]
@Amiditin Дим, это нормально что получился файл на 1200 строк?
https://github.com/torin-asakura/shdvor/blob/feat/bump-hyperion/ui/theme/src/button-colors/button-colors.ts

- у меня ts отваливается при таком количестве union-types, поэтому попробовал вынести в другой файл и подключать параллельно, но по всей видимости так работать не будет.
- только заметил, что цвета везде `rgba(0, 0, 0, 0.00)`
- както можно сгененировать верстку для buttons? на той неделе видел, что ты пушил чтото похожее по названиям коммитов.

**Comment by Amiditin** [comment]
> @Amiditin Дим, это нормально что получился файл на 1200 строк?
> https://github.com/torin-asakura/shdvor/blob/feat/bump-hyperion/ui/theme/src/button-colors/button-colors.ts

Нет, не нормально, ниже пример как должно быть для `buttons`, ты запускаешь команду с методом `secondary`, можешь скинуть команду и ссылку на фигму если не поможет?
```json
{
  "button.primary.default.background": "rgba(34, 197, 94, 1)",
  "button.primary.default.font": "rgba(255, 255, 255, 0.90)",
  "button.primary.default.border": "none",
  "button.primary.hover.background": "rgba(30, 174, 83, 1)",
  "button.primary.hover.font": "rgba(255, 255, 255, 0.90)",
  "button.primary.hover.border": "none",
  "button.primary.focus.background": "rgba(26, 152, 73, 1)",
  "button.primary.focus.font": "rgba(255, 255, 255, 0.90)",
  "button.primary.focus.border": "rgba(34, 197, 94, 0.35)",
  "button.primary.pressed.background": "rgba(23, 130, 62, 1)",
  "button.primary.pressed.font": "rgba(255, 255, 255, 0.90)",
  "button.primary.pressed.border": "rgba(34, 197, 94, 0.35)",
  "button.primary.disabled.background": "rgba(34, 197, 94, 0.55)",
  "button.primary.disabled.font": "rgba(255, 255, 255, 0.65)",
  "button.primary.disabled.border": "none",
}
```

**Comment by kirill-ivanovvv** [comment]
> Нет, не нормально, ниже пример как должно быть для `buttons`. Ты запускаешь команду с методом `secondary`?можешь скинуть команду и ссылку на фигму если не поможет?

- `yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA -o ./src/theme`
- `yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA --secondary`
- почемуто не работает ключ `-o` и все падает в `./theme`, хотя указываю в `./src/theme`
- [фигма](https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=356-4895&node-type=frame&t=SY0B32pnkFyWM0p5-0)

- запускал без метода --secondary, потомучто
```console
[operator@archlinux atls_shdvor]$ yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA --secondary
error: unknown option '--secondary'
```

- запуск без --secondary проходит в обычном режиме, [но генерирует очень много цветов для кнопок](https://github.com/torin-asakura/shdvor/blob/feat/button/ui/theme/theme/colors.ts):
```console
[operator@archlinux atls_shdvor]$ yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA -o ./src/theme
Enter your Figma access token:
figd_4Fio9TG8CNBftH-URvOJO_lTbgxpsUS7bEMHKrWL
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
figma-theme info info Theme successful generated
```

**Comment by Amiditin** [comment]
@kirill-ivanovvv метод не правильно указываешь, нужно 
```
yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA -o ./theme --method secondary
```
для  `-o ./src/theme` нужно чтобы эта папка была создана

**Comment by kirill-ivanovvv** [comment]
> @kirill-ivanovvv метод не правильно указываешь, нужно

по количеству лучше, но [цвета всеравно нули](https://github.com/torin-asakura/shdvor/blob/feat/button/ui/theme/theme/colors.ts)

**Comment by Amiditin** [comment]
> > @kirill-ivanovvv метод не правильно указываешь, нужно
> 
> по количеству лучше, но [цвета всеравно нули](https://github.com/torin-asakura/shdvor/blob/feat/button/ui/theme/theme/colors.ts)

@kirill-ivanovvv  @EdMakriy  дизайн нужно подправить, сейчас генератор работает по структуре: обертка `Frame` с состояниями, потом идёт `Element/Base` и в конце `Text`

<details>

https://www.figma.com/design/pdUi2oYo5kZUHaMAjpFNdp/R46-Product-Design-System-Master?node-id=3482-4556&m=dev
![image](https://github.com/user-attachments/assets/5d4148cb-c56b-4e27-8bda-4d855dd7b688)
</details>

В текущем идёт `Frame` с состояниями и без `Element/Base`, нужно его добавить.

<details>

https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3773-1276&m=dev
![image](https://github.com/user-attachments/assets/57700d9c-300c-452c-9b1a-0b3d85da02c0)
</details>

**Comment by Amiditin** [comment]
В дополнение от `Element/Base` ожидается `border` и `background` стили, от `Text` ожидается `color`

**Comment by kirill-ivanovvv** [comment]
@Amiditin 

> * както можно сгененировать верстку для buttons? на той неделе видел, что ты пушил чтото похожее по названиям коммитов.

генерируется же только appearance. shape вручную перебиваем?

**Comment by Amiditin** [comment]
> генерируется же только appearance. shape вручную перебиваем?

@kirill-ivanovvv да, для shape нет генератора

**Comment by EdMakriy** [comment]
Element/Base задает структуру кнопки, которую потом в Button настраивается под состояния. Тоесть и цвет и бордер и отступы в Element/Base будут перезаписаны в Button.

Вам сделать Element/Base и на его основе сделать все кнопки в Generator/Button с нуля?

**Comment by Amiditin** [comment]
> Вам сделать Element/Base и на его основе сделать все кнопки в Generator/Button с нуля?

@EdMakriy видимо да, нужна структура как в рисе с `Element/Base`

**Comment by EdMakriy** [comment]
https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3816-105&t=Ra1FVUWZpbTfkfem-4

<img width="247" alt="image" src="https://github.com/user-attachments/assets/f4a1e196-f5de-4f3e-b9dc-b9d83b3868a1" />
<img width="319" alt="image" src="https://github.com/user-attachments/assets/6e9b9405-59f5-4cf5-a9e7-7ecd03250d1c" />

Этого достаточно или все кнопки переделать?

**Comment by kirill-ivanovvv** [comment]
> https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3816-105&t=Ra1FVUWZpbTfkfem-4
> 
> <img alt="image" width="247" src="https://private-user-images.githubusercontent.com/165061320/396644304-f4a1e196-f5de-4f3e-b9dc-b9d83b3868a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjYxMDEsIm5iZiI6MTczNDQ2NTgwMSwicGF0aCI6Ii8xNjUwNjEzMjAvMzk2NjQ0MzA0LWY0YTFlMTk2LWY1ZGUtNGYzZS1iOWRjLWI5ZDgzYjM4NjhhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTNmNDM1MTE4MmZhMDVkNTcwZTBiZmU3OGJjNGQ0OTMzM2Y0Y2RiZDViYmYwNGEzMjYwYmQ5MDRkZDIzM2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h56kWspB17wygWR1s5D0USh1jHfYHRBYq1o4Jppq4aw"> <img alt="image" width="319" src="https://private-user-images.githubusercontent.com/165061320/396644381-6e9b9405-59f5-4cf5-a9e7-7ecd03250d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjYxMDEsIm5iZiI6MTczNDQ2NTgwMSwicGF0aCI6Ii8xNjUwNjEzMjAvMzk2NjQ0MzgxLTZlOWI5NDA1LTU5ZjUtNGNmNS1hOWU3LTdlY2QwMzI1MGQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QyMDAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmU1M2Q1MDUxMzIwMmI4NWNmZWM3NjVlZTljZDkxM2JmYTcxNjFhM2JmMGI3YzFiY2MxZDMxYjMyODJkNzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MOxKWfahVnUSoX43_UmsbjW-XPlKzezbwTsr4a99qd4">
> Этого достаточно или все кнопки переделать?

- щас генератор запустил, в цетах - нули
- мне показалось что у нас неправильно то, что нету внутреннего контейнера
вот как Дима предлагает:
![image](https://github.com/user-attachments/assets/56a4d8d4-6f9a-470c-9b16-61c8c3610940)
вот как у новых кнопок:
![image](https://github.com/user-attachments/assets/7b36ebec-30a5-4a75-ae5b-93b053e39668)

@Amiditin подскажи по этому поинту ^

> Этого достаточно или все кнопки переделать?

@EdMakriy вообще да, все нужны

**Comment by Amiditin** [comment]
> * мне показалось что у нас неправильно то, что нету внутреннего контейнера
>   вот как Дима предлагает:
>   ![image](https://private-user-images.githubusercontent.com/70315473/396650799-56a4d8d4-6f9a-470c-9b16-61c8c3610940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjgyMzksIm5iZiI6MTczNDQ2NzkzOSwicGF0aCI6Ii83MDMxNTQ3My8zOTY2NTA3OTktNTZhNGQ4ZDQtNmY5YS00NzBjLTliMTYtNjFjOGMzNjEwOTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDIwMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTJjOTYxZTg5YTE2YmFjOGUxZTM0MTViN2U2YjQ1OTkyYjY2M2Q3YTc3YWZhYTIxYzk2MDM1MGY1NTgyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hzz6kRlliHSlgiYOQjK9nfa1o4oLHGw3CsPQjLr67AU)
>   вот как у новых кнопок:
>   ![image](https://private-user-images.githubusercontent.com/70315473/396650905-7b36ebec-30a5-4a75-ae5b-93b053e39668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjgyMzksIm5iZiI6MTczNDQ2NzkzOSwicGF0aCI6Ii83MDMxNTQ3My8zOTY2NTA5MDUtN2IzNmViZWMtMzBhNS00YTc1LWFlNWItOTNiMDUzZTM5NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDIwMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjE1NzgyOWQ0OTY5MzhkOTQ4MTViZmYwYzUzNmE5OWQ0NzVhZWE4OTYwZWM4YTEwMGFlZjhjMzZhMTVhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9YKS3yhd8KOD4f6Y4Uctyf9OVJiZeyEBT8uWPhiTIkY)
> 
> @Amiditin подскажи по этому поинту ^

Да, верно, `Element/Base` нужен внутри фрейма со свойствами, как обертка над текстом

**Comment by EdMakriy** [comment]
Ок, завтра днем сделаю - это небыстро.

**Comment by EdMakriy** [comment]
- https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3820-200&t=KWa7JfHmFqmjimWN-1
- https://www.figma.com/design/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3816-105&t=KWa7JfHmFqmjimWN-1

**Comment by kirill-ivanovvv** [comment]
> ```
> yarn workspace @ui/theme generate-theme vqze2qxVpYJDKtablQExoA -o ./theme --method secondary
> ```

цвета в тему сгененировал, стили сгенерировал. благодарю

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
текущий ишью пока оставлю. по фрагментам очень недобно лазить, пропускаю наименования
удобнее всего будет поправить имена переменны при помощи `yarn check`, но сейчас много мусорного кода, проверки которого идут вначале. закрывал компоненты заглушками
поэтому лучше всего будет сделать это в конце


#### Текущий статус
- доделал кнопки
- фикс interseption-observer
- фиксил нейминги переменных
- распределял изменения по разным веткам, отправлял ПР
#### Дальнейшие планы
- либо подключусь к компонентам, либо начну мерджить их в основную ветку и отправлять на ПР
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by kirill-ivanovvv** [comment]
Актуальный код в https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion
