### ISSUE TITLE
Работа с данными

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shdvor#15]
### Задача

Наполнить сайт данными с вордпресса

### Как я это вижу

Все запросы нужно адресовывать на https://wp.shdvor.pro/graphql

Данные с вордпресса можно получать по Graphql

Также есть плейграунд, в который можно перейти нажав сюда

![image](https://user-images.githubusercontent.com/62806448/177562629-500c3842-ed99-45fb-b2dc-cc19868f4eaa.png)

По похожей схеме работают https://misik.pro и https://dream-team.tech

### Подводные камни

Некоторые записи могут иметь "мусорные" символы. Чтобы избавиться от них строку можно прогнать через подобную функцию

<details>

```typescript
const normalizeString = (string) =>
  string
    .replace(/(<p>|<\/p>)/g, '')
    .replace(/&#8211;/g, '-')
    .replace(/&#8212;/g, '-')
    .replace(/<meta charset="utf-8">/g, '')
    .replace(/<br\/>/g, '')
    .replace(/<br \/>/g, '')
```

</details>

**Comment by brusselboy** [comment]
## Вопросы по вордпрессу

@TFK70 

Начнём с блога. Как я понимаю уже имеются статьи и нужно просто сделать запрос и их получить, вот они - [click](https://wp.shdvor.pro/wp-admin/edit.php)

1. Если я правильно понял они готовы и можно просто по запросу получить их, не могу найти этот запрос в плейграунде.
2. Возможно я ошибаюсь и их нужно в ручную через мутации в плейграунде создать, только опять же какая мутация за это отвечает и когда создашь статьи, через какой запрос обращаться чтобы эти статьи получить? (Если этот пункт верный, остается открытым вопрос, что тогда это за [статьи](https://wp.shdvor.pro/wp-admin/edit.php))

**Comment by brusselboy** [comment]
@TFK70 Могу ли я как-то загрузить картинки в вордпрессе?

А то когда делаю запрос: 

<details>

```
query GetPosts {
  posts {
    nodes {
      id
      title
      date
      featuredImage {
        node {
          mediaItemUrl
        }
      }
    }
  }
}

```

</details>

Вместо ссылки приходит `null`

<details>

```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "id": "cG9zdDoxNDI3",
          "title": "Аргонодуговая сварка",
          "date": "2020-07-09T17:00:39",
          "featuredImage": null
        },
        {
          "id": "cG9zdDoxNDEy",
          "title": "Хранение шин",
          "date": "2020-07-07T20:56:57",
          "featuredImage": null
        },
        {
          "id": "cG9zdDoxNDA2",
          "title": "Ремонт стальных дисков",
          "date": "2020-07-07T19:25:09",
          "featuredImage": null
        },
        {
          "id": "cG9zdDoxMzk3",
          "title": "Ремонт литых дисков",
          "date": "2020-07-07T18:14:35",
          "featuredImage": null
        }
      ]
    }
  }

```

</details>

**Comment by TFK70** [comment]
@brusselboy для начала нужно загрузить нужное изображение в медиафайлы - https://wp.shdvor.pro/wp-admin/upload.php

Потом зайти на страницу поста и загрузить изображение в featured image

Если блок featured image не отображается - погугли как его включить

**Comment by brusselboy** [comment]
## Вопросы

@TFK70 

1. Какой запрос отвечает за [просмотры](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=484%3A1273) у поста? Из счётчиков нашёл там только счётчик комментариев.
2. Как отформатировать мейн текст, чтобы он был как [здесь](https://wp.shdvor.pro/wp-admin/post.php?post=1412&action=edit). Из идей только вырезать текст по кускам и уже их обрабатывать, мейби есть какой-то способ получше? 

Сейчас он выглядит так:
<details>

![image](https://user-images.githubusercontent.com/35490768/177805331-5b9ba402-4fa5-4331-8c69-5e017f40a42b.png)

</details>

 3. По поводу картинок не до конца разобрался, загрузить загрузил, но **featured image** не нашёл. Нагуглил вот [это](https://ru.stackoverflow.com/questions/1359012/%D0%9D%D0%B5-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82-%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5-%D1%84%D0%BE%D1%82%D0%BE-featured-image-advanced-custom-fields-wordpress), пишут про "настройки экрана", у меня там нету **featured image**, на странице поста тоже ни намёка. По этому вопросу хотелось бы в дисе созвониться.
 4. Со всем остальным текстом допустим с [заголовком](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=475%3A1250) и со всем таким похожим текстом (у [кнопок](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=484%3A1273) и т.д) мы как работаем, тоже всё с бека запрашиваем?

**Comment by TFK70** [comment]
@brusselboy через [ACF](https://wp.shdvor.pro/wp-admin/edit.php?post_type=acf-field-group)

**Comment by brusselboy** [comment]
## Проблема с ACF

@TFK70 

### Описание

Создал группу полей для [контактов](https://wp.shdvor.pro/wp-admin/post.php?post=2026&action=edit), для каждого элемента создал имя поля **object** и значение по умолчанию, но в graphQL почему-то берется только первое значение **contacts**, т.к он идёт первый:
<details>

![image](https://user-images.githubusercontent.com/35490768/178693892-3c7c237b-4d04-4fb5-aaae-d513748f36e2.png)

</details>

Также сделал условие отображения чтобы было связано с [Contacts Fragments](https://wp.shdvor.pro/wp-admin/edit.php?post_type=contacts_fragments)

<details>

![image](https://user-images.githubusercontent.com/35490768/178694755-39992737-b9b5-42ce-95c7-c3b1e7d3c1f1.png)

</details>

### Материалы

Запрос:
<details>

```
query GetFragments {
  contactsFragments {
    nodes {
      title
      fragmentParams {
        object
      }
    }
  }
}
```

</details>

Ответ: 

<details>

```
"data": {
    "contactsFragments": {
      "nodes": [
        {
          "title": "me@busforwork.ru",
          "fragmentParams": {
            "object": "contacts"
          }
        },
        {
          "title": "+7 995 116 1615",
          "fragmentParams": {
            "object": "contacts"
          }
        },
        {
          "title": "Часы работы",
          "fragmentParams": {
            "object": "contacts"
          }
        },
        {
          "title": "Адрес",
          "fragmentParams": {
            "object": "contacts"
          }
        },
        {
          "title": "Контакты",
          "fragmentParams": {
            "object": "contacts"
          }
        }
      ]
    }
  }
```

</details>

### Вопрос

Как сделать, чтобы у каждого элемента **object** был индивидуальный?

Чтобы выглядело как-то так:

<details>

```
"data": {
    "contactsFragments": {
      "nodes": [
        {
          "title": "me@busforwork.ru",
          "fragmentParams": {
            "object": "email"
          }
        },
        {
          "title": "+7 995 116 1615",
          "fragmentParams": {
            "object": "telephone"
          }
        },
        {
          "title": "Часы работы",
          "fragmentParams": {
            "object": "workingHours"
          }
        },
        {
          "title": "Адрес",
          "fragmentParams": {
            "object": "address"
          }
        },
        {
          "title": "Контакты",
          "fragmentParams": {
            "object": "contacts"
          }
        }
      ]
    }
  }
```

</details>

**Comment by TFK70** [comment]
@brusselboy какой статус?

**Comment by brusselboy** [comment]
## Не проходит чек с инсталляцией

@TFK70 

### Описание

Не проходит чек с инсталляцией, ошибка связана с `.pnp.loader.mjs`, прогуглил её - вот что [нашел](https://github.com/yarnpkg/berry/issues/4778). 
Поменял версию с 3.2.1 -> 3.2.2 + проинсталился, ошибка не ушла

### Логи
[link](https://github.com/torin-asakura/shdvor/actions/runs/3183766796/jobs/5191377428)

<details>

```
 ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
  ➤ YN0007: │ root-workspace-0b6124@workspace:. must be built because it never has been before or the last one failed
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR (node:1662) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR (Use `node --trace-warnings ...` to show where the warning was created)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR node:internal/errors:477
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     ErrorCaptureStackTrace(err);
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     ^
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR 
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/runner/work/shdvor/shdvor/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at new NodeError (node:internal/errors:387:5)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at async Promise.all (index 0)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at async loadESM (node:internal/process/esm_loader:91:5)
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR     at async handleMainPromise (node:internal/modules/run_main:65:12) {
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR   code: 'ERR_LOADER_CHAIN_INCOMPLETE'
  ➤ YN0000: │ root-workspace-0b6124@workspace:. STDERR }
  ➤ YN0009: │ root-workspace-0b6124@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-bd25e361/build.log)
```

</details>

### Вопрос
Как пофиксить?

**Comment by TFK70** [comment]
@brusselboy локально же у тебя всё норм?

**Comment by brusselboy** [comment]
> @brusselboy локально же у тебя всё норм?

+

**Comment by carminio** [comment]
## Получение списка цен радиусов

@TFK70 

### Описание
[Проблема](https://github.com/torin-asakura/shdvor/pull/17#discussion_r997590512) заключается в том, что запрашиваем цены радиусов в виде:
```
price: {
r12
r13
r14
...
}

```

и если на беке убрать радиус, то фронт будет запрашивать несуществующее поле. 
Было предложено использовать wildcard, то есть получать цены на радиусы в виде `price: { * }`, но погуглив пришел к тому, что в gql такого нету, вот топик из репы самого gql - [link](https://github.com/graphql/graphql-spec/issues/127)

### Вопросы
1. Правильно ли я понял посыл использования wildcard и существует ли его реализация?
2. Еще из этого [коммента](https://github.com/torin-asakura/shdvor/pull/17#discussion_r997590512) было предложено завернуть в переменную. Отсюда вопрос: что завернуть в переменную и как это избавит от необходимости запрашивать с бека каждый радиус?

**Comment by TFK70** [comment]
@carminio запрашивай схему, поиграйся с этими запросами:

```gql
query A {
  __schema {
    queryType {
      fields {
        name
        type {
          fields {
            name
          }
        }
        args {
          name
          description
          defaultValue
        }
      }
    }
  }
}

```

Отсюда будешь получать радиусы

**Comment by carminio** [comment]
@TFK70 

### Запрос:

```gql
query Query {
  __schema {
    types {
      name
      fields {
        name
        type {
          fields {
            name
          }
        }
      }
    }
  }
}
```

### Ответ:

```
{
              "name": "services",
              "type": {
                "fields": [
                  {
                    "name": "edges"
                  },
                  {
                    "name": "nodes"
                  },
                  {
                    "name": "pageInfo"
                  }
                ]
              }
},
```

### Вопрос
Как получить то что находится внутри nodes?

**Comment by TFK70** [comment]
@carminio тебе нужен `Service_Servicesparams_Price`, ты же получаешь gql типы в ответе, у тебя вся схема есть

Мог бы достать название типа из инспектора справа или **просто в поиске вбить r12**

![image](https://user-images.githubusercontent.com/62806448/196422496-4e4a8a88-8960-4164-accf-835559a32887.png)

**Comment by carminio** [comment]
@TFK70 
получил `Service_Servicesparams_Price`, но мне же нужно получать и стоимость, а стоимость находится в `services`, или какой замысел у этого? Получить радиусы из `Service_Servicesparams_Price` потом эти радиусы собрать и передать в другой запрос?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/35490768/196425338-35b66937-91f7-48cb-9922-98852a16d2f5.png">

**Comment by TFK70** [comment]
@carminio да, а как ты хотел? Еще раз: ты получаешь только **схему** по которой делаются запросы

**Comment by carminio** [comment]
## Ошибка на клиенте при запросе схемы

@TFK70 

### Описание
Сделал запрос схемы, вызвал её, появилась ошибка

### Лог
```
Error: GraphQL introspection is not allowed, but the query contained __schema or __type
```

### Вопрос

Возможно ли отключить этот блок? 
Я нашел только вариант через new ApolloServer, через new ApolloClient сделать нельзя

```js
const server = new ApolloServer({
  typeDefs,
  resolvers,
  introspection: process.env.NODE_ENV !== 'production'
});
```

**Comment by carminio** [comment]
## Ошибка после передачи радиусов

@TFK70 

### Описание
[Получаю](https://github.com/torin-asakura/shdvor/blob/feat/data/globals/data/src/data/queries/schema.query.ts#L24) список радиусов, формирую их в массив и передаю в запрос после получаю ошибку. Проще посмотреть код, чтобы понять что происходит - [link](https://github.com/torin-asakura/shdvor/blob/feat/data/globals/data/src/data/queries/services.query.ts#L6-L43)

### Лог

```
Server Error
GraphQLError: Syntax Error: Expected Name, found "[".
```

Ошибка происходит из-за того, что сначала приходит промис, только после появляется массив с радиусами. Но т.к пришел промис первым, он и [подставляется в запрос](https://github.com/torin-asakura/shdvor/blob/feat/data/globals/data/src/data/queries/services.query.ts#L43).

Так выглядит сформированный массив:
`['r12', 'r13', ....]`

### Вопрос
Как передать в [запрос](https://github.com/torin-asakura/shdvor/blob/feat/data/globals/data/src/data/queries/services.query.ts#L43) массив из радиусов

**Comment by TFK70** [comment]
@carminio погоди, так ты и передаешь промис, потренируй асинхронщину:

попробуй

```typescript
          price {
              ${await getRadii()}
          }
```

**Comment by TFK70** [comment]
@carminio 

> но на втором этапе где нужно вставлять код в какой-то файл single.php идея провалилась, тк такого файла в нашей теме нет.

Тема в вп - это клиент. У нас вместо темы свой клиент, поэтому никакие скрипты в тему вставлять не нужно тк бессмысленно. Но, тем не менее, вставить скрипт который будет инкрементить счётчик просмотров все-равно нужно

> Необходима помощь разобраться как сделать счетчик без плагина (код который добавлял в graphql это решение без плагина), либо с плагином, разницы нет, результат все равно один и тот же

Плагин тебе энивей нужен, просто ты его юзаешь по-другому. Тот код который ты вставлял просто добавляет счетчик в gql схему и ты можешь его получить по gql, осталось счётчик инкрементить

## Теперь к решению

Хз че за код этот чувак предложил чтобы `view_count` получать, но он не работает, переписал на это:

```php
  register_graphql_field( 'Post', 'viewCount', [ 
    'type' => 'Int',
    'description' => __( 'The number of times the post was viewed', 'your-textdomain' ),
    'resolve' => function( $post, $args, $context, $info ) {
      // $post is an instance of a WPGraphQL Post model, 
      // so we can get the ID from the post, and then get meta from that post
      // by calling get_post_meta()
      $view_count = pvc_post_views( $post->postId );
      
      // if there's any count value, return it, otherwise return 0
      return isset( $view_count ) ? absint( $view_count ) : 0;
    }
  ]);
```

Ещё добавил отдельно gql мутацию на инкремент счётчика, её тебе нужно вызывать каждый раз когда кто-то тыкает на пост:

```php
	register_graphql_mutation('incrementCounter', [ 
    'inputFields' => [
		'post_id' => [
			'type' => 'Int',
			'description' => _('Post id')
		]
	],
	'outputFields' => [
		'viewCount' => [
			'type' => 'Int',
			'description' => _('View count')
		],
		'success' => [
			'type' => 'Boolean',
			'description' => _('Wrote to db succesfully')
		]
	],
    'description' => __( 'Increment post views counter' ),
    'mutateAndGetPayload' => function( $input, $context, $info ) {
	  $pid = $input['post_id'];
      $view_count = pvc_post_views( $pid );
      $success = pvc_update_post_views($pid, $view_count + 1);
	  return [
		  "viewCount" => $view_count + 1,
		  "success" => $success
	  ];
    }
  ]);
```

```gql
mutation D {
  incrementCounter(input: {post_id: 1397}) {
    viewCount
    success
  }
}
```

И плагин не трогай, я там тоже кое-что поправил, если его переустановить - всё слетит

**Comment by carminio** [comment]
- [ ] Обновить верстку в соотвествии с дизайном
- [ ] Переделать работу с данными для услуг

Общий эстимейт 2 дня
