### ISSUE TITLE
Фикс ошибок `dependabot`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#168]
### С чем связан запрос на фичу?

Необходимо исправить замечания `dependabot`

### Расскажите как вы это себе видите

- берем только `high`
- фиксим по мере возможности

### Критерии готовности выполнения задачи

- замечания исправлены
- функционал приложений работает

### Материалы

https://github.com/torin-asakura/shdvor/security/dependabot?page=2&q=is%3Aopen

**Comment by TorinAsakura** [comment]
это не ошибки, это уязвимости
