### ISSUE TITLE
Обновления в дизе

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shdvor#28]
### Задача

Обновить дизайн с сайтом

### Референс

https://github.com/torin-asakura/shdvor/pull/17#discussion_r998623010

**Comment by TorinAsakura** [comment]
@dakand https://github.com/torin-asakura/shdvor/issues/29 кузова приняты и уже интегрированны. Ждём тебя бро;

**Comment by dakand** [comment]
> Таблица

А куда интегрированы? Что от меня требуется?

**Comment by TorinAsakura** [comment]
> > Таблица
> 
> А куда интегрированы? Что от меня требуется?

в бизнес уже интегрированны, они уже заведены в кассу и парни с ними работают

**Comment by TorinAsakura** [comment]
> > Таблица
> 
> А куда интегрированы? Что от меня требуется?

требуется интегрировать кузова в дизайн, Саша

Написал это на случай, если вдруг не ясно)

**Comment by dakand** [comment]
> > > Таблица
> > 
> > 
> > А куда интегрированы? Что от меня требуется?
> 
> требуется интегрировать кузова в дизайн, Саша
> 
> Написал это на случай, если вдруг не ясно)

По-прежнему не ясно. Кузова были и есть как на странице услуги, так и в заявке. Экран с альтернативным вариантом услуги я добавил прям во время созвона. По таблице которую я прикрепил никаких изменений не увидел, в т.ч. вопрос по грузовым для меня остаётся открытым.

**Comment by TorinAsakura** [comment]
https://github.com/torin-asakura/shdvor/issues/29#issuecomment-1285547011

**Comment by dakand** [comment]
@TorinAsakura я внес правки в дизайн. Постарался внести логику, поэтому сейчас напишу своё видение с точки зрения UX.
Мы решили, что у нас услуга будет от кузова - ок. Но множить внутри сайта услугу на однотипные по кузову я не вижу смысла. Пусть на страниц услуг все услуги будут одноименными и уникальными, а цена будет в формате "от N руб." Также я добавил к каждой карточке в превью [тег](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=312%3A104) "в среднем ...", чтобы не создавать сильно обманчивое впечатление о ценах (как средний чек в рестике). Вот так. А на самой странице мы уже делаем модификатор цен по кузову и радиусу. Важный момент @TFK70 @carminio - на странице услуги всегда должны быть предустановленные параметры, но в заявке изначально все радиусы дефолтные.

Вопросы:
1. В таблице в ремонте дисков заполнена только колонка "легковые". Это значит, что услуга распространяется только на легковые авто или то, что стоимость услуги не зависит от кузова, а только от радиуса?
2. Снятие колес. Уже говорил, что добавлять такую услугу не очень клиентоориентированно. Автолюбители привыкли, что им предоставляют одну услугу по одной цене. А снятие колес это одно из действий каждой из услуг. Создавая такую услугу отдельной карточкой есть вероятность тупняка со стороны пользователя (Нужно ли суммировать эти услуги? Они предлагают сами снять мне колеса?). Даже если 1 из 100 почему-то хочет только снять колеса - пусть звонит и узнает можно ли и сколько будет стоить (он должен сам понимать что это редкая услуга).
3. Снятие колес нам не нужно, имхо. А вот "Замена колес" очень даже. Это когда у тебя отдельный комплект колес, а не резины и тебе их нужно поменять без снятия шин с диска.

**Comment by TorinAsakura** [comment]
> @TorinAsakura я внес правки в дизайн. Постарался внести логику, поэтому сейчас напишу своё видение с точки зрения UX. Мы решили, что у нас услуга будет от кузова - ок. Но множить внутри сайта услугу на однотипные по кузову я не вижу смысла. Пусть на страниц услуг все услуги будут одноименными и уникальными, а цена будет в формате "от N руб." Также я добавил к каждой карточке в превью [тег](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=312%3A104) "в среднем ...", чтобы не создавать сильно обманчивое впечатление о ценах (как средний чек в рестике). Вот так. А на самой странице мы уже делаем модификатор цен по кузову и радиусу. Важный момент @TFK70 @carminio - на странице услуги всегда должны быть предустановленные параметры, но в заявке изначально все радиусы дефолтные.
> 
> Вопросы:
> 
> 1. В таблице в ремонте дисков заполнена только колонка "легковые". Это значит, что услуга распространяется только на легковые авто или то, что стоимость услуги не зависит от кузова, а только от радиуса?
> 2. Снятие колес. Уже говорил, что добавлять такую услугу не очень клиентоориентированно. Автолюбители привыкли, что им предоставляют одну услугу по одной цене. А снятие колес это одно из действий каждой из услуг. Создавая такую услугу отдельной карточкой есть вероятность тупняка со стороны пользователя (Нужно ли суммировать эти услуги? Они предлагают сами снять мне колеса?). Даже если 1 из 100 почему-то хочет только снять колеса - пусть звонит и узнает можно ли и сколько будет стоить (он должен сам понимать что это редкая услуга).
> 3. Снятие колес нам не нужно, имхо. А вот "Замена колес" очень даже. Это когда у тебя отдельный комплект колес, а не резины и тебе их нужно поменять без снятия шин с диска.

1. Если у нас нет ничего кроме легкового тогда зачем выносить это в отдельную категорию? Нужно было оставить как есть @carminio - отвечая на твой вопрос @dakand да, тут только от радиуса.
2. Тут я с тобой полностью согласен, и я уже вроде тебе говорил, что её можно просто "закладывать" в основные услуги, так как на сайте такая услуга как "снятие колеса" выглядит отстойно
3. Плюсую. Надо просто понять что туда будет входить, чтобы я это на "землю" протолкнул

**Comment by carminio** [comment]
@dakand в дизайне ещё не хватает услуги "Монтаж и демонтаж", стоимость указывается за одно колесо. Данная услуга есть в кассе, она также распространяется на все кузова, мы можем добавить эту услугу в дизайн?

**Comment by dakand** [comment]
> @dakand в дизайне ещё не хватает услуги "Монтаж и демонтаж", стоимость указывается за одно колесо. Данная услуга есть в кассе, она также распространяется на все кузова, мы можем добавить эту услугу в дизайн?

@TorinAsakura а разве "монтаж и демонтаж" и "шиномонтаж" это не одинаковые услуги?

**Comment by TorinAsakura** [comment]
@dakand Зависит от интерпретации. Но, под шиномонтажём находится ряд услуг, помимо монтажа/демонтажа. Ч могу детализировать понятие монтажа/демонтажа, если это поможет, но, я бы просто смотрел лучшие практики.

**Comment by dakand** [comment]
> @dakand Зависит от интерпретации. Но, под шиномонтажём находится ряд услуг, помимо монтажа/демонтажа. Ч могу детализировать понятие монтажа/демонтажа, если это поможет, но, я бы просто смотрел лучшие практики.

Ну я к тому что у нас есть услуга "Шиномонтаж" в дизайне и стоит ли нам добавлять "Монтаж и демонтаж". Если да, то услугу "Шиномонтаж" убираем?

**Comment by TorinAsakura** [comment]
@dakand Повторюсь: шиномонтаж это не услуга, это ряд услуг. Монтаж/демонтаж относят именно к этой категории.

**Comment by dakand** [comment]
> @dakand Повторюсь: шиномонтаж это не услуга, это ряд услуг. Монтаж/демонтаж относят именно к этой категории.

@TorinAsakura ты просто напиши что нам оставить. Я не знаю ваше позиционирование и не вижу в таблице позицию шиномонтаж. Значит мы её убираем, оставляя "монтаж и демонтаж"?

**Comment by TorinAsakura** [comment]
@dakand Оставь шиномонтаж

**Comment by TorinAsakura** [comment]
> > @dakand в дизайне ещё не хватает услуги "Монтаж и демонтаж", стоимость указывается за одно колесо. Данная услуга есть в кассе, она также распространяется на все кузова, мы можем добавить эту услугу в дизайн?
> 
> @carminio тогда шиномонтаж оставляем, но эта услуга по конфигурации как во вкладке "Монтаж и демонтаж". Я ещё добавил одну услугу "Замена колес". Картинку добавлю чуть позже, по наполнению @TorinAsakura думаю даст ответ. В целом там все банально должно быть - снять одни колеса, одеть другие.

Ответ на что я должен буду дать?

**Comment by dakand** [comment]
> Ответ на что я должен буду дать?

_"Плюсую. Надо просто понять что туда будет входить, чтобы я это на "землю" протолкнул"_.
Речь об услуге замены колес и её наполнении.

**Comment by TorinAsakura** [comment]
> > Ответ на что я должен буду дать?
> 
> _"Плюсую. Надо просто понять что туда будет входить, чтобы я это на "землю" протолкнул"_. Речь об услуге замены колес и её наполнении.

Услуги на "земле" у нас сформированы и для земли они могут немного отличаться от тех, что у нас будут в паблике.

Закинул доступ в кассу в личку.
