### ISSUE TITLE
Формирование цен

### ISSUE THREAD

**Issue by carminio** [torin-asakura/shdvor#29]
- [x] Составить таблицы цен для услуг
- [x] Внести изменения в aqsi

**Comment by carminio** [comment]
@TorinAsakura 

[untitled folder.zip](https://github.com/torin-asakura/shdvor/files/9821701/untitled.folder.zip)

**Comment by TorinAsakura** [comment]
@carminio на будущее - это делается не в проприетарном софте яблочном, а в облачном гугле, чтобы это смог посмотреть каждый не запускаю аппу и не уходя из браузера

**Comment by TorinAsakura** [comment]
@carminio жду решения по переобувке, так как текущие цены это фарш

**Comment by carminio** [comment]
@TorinAsakura 

Переделал переобувку, можно смотреть -> [link](https://docs.google.com/spreadsheets/d/17HOWS_FMN_ScZWSw5vi6u8sohs_yQdfikivUMYm42OU/edit?usp=sharing)

**Comment by carminio** [comment]
@TorinAsakura 

Перенёс в акси, можно смотреть

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> Перенёс в акси, можно смотреть

Я тебя просил внимательней работать с кассой. Ну ты чо ёмаё?

![Снимок экрана 2022-10-21 в 14 58 53](https://user-images.githubusercontent.com/3940885/197190764-a4fc9e81-4da7-48c7-ba6d-0638caac1461.png)

**Comment by TorinAsakura** [comment]
![Снимок экрана 2022-10-21 в 15 18 37](https://user-images.githubusercontent.com/3940885/197193975-20be114d-02ac-4f92-9055-d70ccca7f2c5.png)

**Comment by carminio** [comment]
> ![Снимок экрана 2022-10-21 в 15 18 37](https://user-images.githubusercontent.com/3940885/197193975-20be114d-02ac-4f92-9055-d70ccca7f2c5.png)

готово

**Comment by TorinAsakura** [comment]
Вроде выглядит нормально. Продолжаем.
