### ISSUE TITLE
Совместимость дизайна и фронта

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shdvor#31]
### Правки и ошибки:
- [x] У шапки темный бг, а должен быть прозрачным. [Скрин](https://disk.yandex.ru/i/1QBGEChrUBJmEg)
- [x] Хиро должен быть во всю высоту вьюпорта. Предыдущий скрин.
- [x] После брейкпоинта 1440px начинают ехать блоки. [Скрин](https://disk.yandex.ru/i/FXfgtIZPlVGIkw)
- [x] В "Наши услуги" паддинг увеличить до 120 px (верхний и нижний, но только в этом блоке). Если возможно это сделать для бп >1600px или fullHD, то применить только к ним. [Скрин](https://disk.yandex.ru/i/7V-DG4pT1v2sSA).
- [ ] Данный контрол не работает. [Скрин](https://disk.yandex.ru/i/g_EDyc266mb6fg)
- [ ] Другие картинки в карусели должны увеличиваться, если мы переключаемся вправо/влево. Также сейчас изображение внутри неправильных контейнеров "плющит". Скоре всего задан 100% как для высоты, так и для ширины. [Скрин](https://disk.yandex.ru/i/-Xj6OFFbEbjIAA)
- [x] "Услуги" и "Контакты" в шапке через раз срабатывают. Скорее всего задержка в скорости загрузки, но при нажатии на эти страницы не появляется полоса загрузки страницы браузера и непонятно загружается ли он или нет. Если проблема все же в загрузке, то она оч долгая.
- [x] Логотип в шапке не ведёт на главную
- [x] При наведении на [превью услуги](https://disk.yandex.ru/i/XCmfXzGzlX6iVA) добавить анимацию: 10px вверх, 150ms, ease
- [x] [Этот контейнер](https://disk.yandex.ru/i/d4YpM3m_jpiTig) нужно флексом делать и его содержимое тоже.
- [x] Отступ между кузовом и радиусом великоват. [Скрин](https://disk.yandex.ru/i/MUT9EXjb87KDhQ)
- [x] Отступ между чекбоксом и "Балансировкой" маленький. Предыдущий скрин.
- [x] У тега надо паддинги поправить. У меня в дизайне 6px, 10px. Если будут великоваты, просто увеличь на 2-4 pх по бокам.
- [x] В записи блога фотка зашакаленная, видимо юзал ту же, что и для превью. Вот [хайрез](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0%3A1), экспортируй лучше x1.5
- [x] Нужно, чтобы юзер видел конец дропдауна + запас минимум 40px. [Скрин](https://disk.yandex.ru/i/l8pYlUMuTY8yHw)
- [x] Поле телефона принимает данные с текстом.
- [x] У кнопки закрытия окна записи должна быть hover анимация
- [x] В Hero, у кнопок соц сетей появился бордер, которого нет в дизайне.
- [x] При нажатии на поинты колеса на главной, подсказки открываются неправильно - под подсказкой остается расстояние.
- [x] Межстрочник у инпутов увеличить до 140%

**Comment by carminio** [comment]
@TFK70 
> У шапки темный бг, а должен быть прозрачным

такая история как и с мисиком, уберу бекграунд и контент из хедера будет сливаться с контентом сайта.
Как лучше поступим, уберем просто темный вариант, а белый оставим или же 100% оставляем прозрачным и всё равно что он будет сливаться с другим контентом

**Comment by carminio** [comment]
@dakand 
> У шапки темный бг, а должен быть прозрачным

такая же история как и с мисиком, уберу бекграунд и контент из хедера будет сливаться с контентом сайта.
Как лучше поступим, уберем просто темный вариант, а белый оставим или же 100% оставляем прозрачным и всё равно что он будет сливаться с другим контентом

**Comment by dakand** [comment]
> @dakand 
> 
> > У шапки темный бг, а должен быть прозрачным
> 
> 
> 
> такая же история как и с мисиком, уберу бекграунд и контент из хедера будет сливаться с контентом сайта.
> 
> Как лучше поступим, уберем просто темный вариант, а белый оставим или же 100% оставляем прозрачным и всё равно что он будет сливаться с другим контентом

@carminio так просто пусть при скролле 100px фон становится белым

**Comment by carminio** [comment]
@dakand 

> Данный контрол не работает.

Здесь нужно больше информации, в каком именно браузере не работает? Также заметил что у тебя установлено какое-то расширение для скачивания картинок (которое как раз возможно и блочит), попробуй его отключить и перезагрузить страницу, после чего воспользоваться контролом

-----

> Другие картинки в карусели должны увеличиваться, если мы переключаемся вправо/влево. Также сейчас изображение внутри неправильных контейнеров "плющит". Скоре всего задан 100% как для высоты, так и для ширины.

Здесь все работает, при переключении слайдов активный слайд увеличивается, неактивные уменьшаются (то есть логика отрабатывает). То что на скрине, это скорее всего из-за того, что ты переключился с мобилки на десктоп, в таком случае да, при изменении брейкпоинтов свайперу становится плохо.

Тут вопрос к @TFK70 насколько это критично? Имеет ли вообще смысл дублировать компоненты, ибо сейчас используется [1 Слайдер](https://github.com/torin-asakura/shdvor/blob/fix/finalize-layout/site/fragments/works-examples-fragment/src/works-examples.component.tsx#L76-L81) внутри которого настроены брейкпоинты, просто если рассматривать ситуацию с позиции юзера: я зашел на сайт с мобилки, зачем мне переключаться на десктоп версию? И наоборот, зашел с пк - зачем мне мобайл версия сайта?

-----

> "Услуги" и "Контакты" в шапке через раз срабатывают. Скорее всего задержка в скорости загрузки, но при нажатии на эти страницы не появляется полоса загрузки страницы браузера и непонятно загружается ли он или нет. Если проблема все же в загрузке, то она оч долгая.

Тут могу только предположить и предложить.

Предположить: 
Всё рендерится на сервере и пока страница не отрендерится, страница не загрузится. Возможно из-за этого такой долгий лоадинг. Здесь может что добавит @TFK70 

Предложить:
Можно при клике на ссылку, пока идет загрузка (которая никак не идентифицируется), просто отрисовывать на весь экран лоадер, пульсирующий лого или что-то в этом духе

**Comment by TFK70** [comment]
> Тут вопрос к @TFK70 насколько это критично? Имеет ли вообще смысл дублировать компоненты, ибо сейчас используется [1 Слайдер](https://github.com/torin-asakura/shdvor/blob/fix/finalize-layout/site/fragments/works-examples-fragment/src/works-examples.component.tsx#L76-L81) внутри которого настроены брейкпоинты, просто если рассматривать ситуацию с позиции юзера: я зашел на сайт с мобилки, зачем мне переключаться на десктоп версию? И наоборот, зашел с пк - зачем мне мобайл версия сайта?

Незачем. Ты даже если эти слайдеры продублируешь - у тебя не будут переключаться брейкпоинты в рантайме, так уж свайпер работает.
@dakand чтобы нормально протестировать слайдер на разных брейкпоинтах - нужно сначала изменить вьюпорт, а потом перезагрузить страницу, чтобы слайдер переинициализировался с учётом нового вьюпорта

> Предложить:
Можно при клике на ссылку, пока идет загрузка (которая никак не идентифицируется), просто отрисовывать на весь экран лоадер, пульсирующий лого или что-то в этом духе

Насчёт прелоадера пожалуй соглашусь

> Предположить:
Всё рендерится на сервере и пока страница не отрендерится, страница не загрузится. Возможно из-за этого такой долгий лоадинг. Здесь может что добавит @TFK70

Да, возможно из-за этого. Можно рассмотреть вариант с пре-фетчем абсолютно всех данных для всех страниц, но здесь нужно будет поресёчить и поизучать можно ли такое без боли реализовать на нексте, но вариант с прелоадером выглядит пока разумнее, тем более такое уже реализовано на misik.pro, у нас есть наработки

**Comment by carminio** [comment]
@dakand пока не нужно никаких лоадеров прелоадеров, внёс изменения для загрузки страниц

**Comment by TorinAsakura** [comment]
@TFK70 статус?

**Comment by TFK70** [comment]
> @TFK70 статус?

https://github.com/torin-asakura/shdvor/pull/32 - это пр закроет, уже финалится

**Comment by TFK70** [comment]
@dakand предлагаю добавить на сайт page loader progress, как на гитхабе, синяя полоска сверху:

https://user-images.githubusercontent.com/62806448/199205981-ac6e58f7-c526-42ba-a5cd-932fbb073068.mov

Что скажешь?

**Comment by dakand** [comment]
> @dakand предлагаю добавить на сайт page loader progress, как на гитхабе, синяя полоска сверху:
> 
>  2022-11-01.14.44.58.mov 
> Что скажешь?

Я не против, https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=3044%3A3248

**Comment by TFK70** [comment]
@carminio можешь начинать имплементить, из инструментов советую взглянуть на [PACE](https://codebyzach.github.io/pace/) (или что-то подобное), это вроде как раз то что нужно
