### ISSUE TITLE
проблемы с производительностью

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/shdvor#37]
https://disk.yandex.ru/i/Mu1xEPuhujtSXA - контекст находится в видео

если вкратце:
- страница открывается больше 2-х секунд - это критично, при условии, что нет абсолютно никакой нагрузки
- при переходах со страницы на страницу время может затрачиваться случайным образом, где-то быстро, где-то нет, и это уже при условии, что я прыгал с кэшом, а на старте вычистил кэш

также случайно поймал баг с картой

**Comment by TorinAsakura** [comment]
А это я попытался перейти на главную через лого

![Снимок экрана 2022-11-18 в 23 31 31](https://user-images.githubusercontent.com/3940885/202797082-36b0b912-52b3-4e02-b18d-b22cb380d628.png)

**Comment by TorinAsakura** [comment]
Что-то у нас очень много яндекса, вам так не кажется?

**Comment by carminio** [comment]
@TFK70 нашел причину почему при переходах между страницами рандомно затрачивается разное время, то быстро, то медленно, проблема была в кэше, исправил. Но самая первая загрузка по прежнему составляет более двух секунд, скорее всего из-за большого html файла.

Также неясно почему так много яндекса, мб это просто отображаются старые загруженные и при переходах они все не подгружаются постоянно

**Comment by TorinAsakura** [comment]
@carminio так не пойдёт
@TFK70 возьми под свой контроль и исследуйте причины

**Comment by carminio** [comment]
@TFK70 

### Убрал server-side-props 
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/35490768/203273721-01ff733b-743b-41ad-983b-6845546c7bf0.png">

### С server-side-props
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/35490768/203274642-6f856e26-a5e6-4c06-9bdf-4a39d772b85c.png">

### Вывод:
без SSP документ весит 12.78кб
с SSP весит 22.32кб 
Не думаю что здесь влияет именно вес самого документа, скорее всего ответ от сервера

**Comment by TFK70** [comment]
@carminio да, дело в ответе от сервера

Здесь в любом случае придётся чем-то жертвовать, раз уж весь контент мы берём с вп. Вижу 2 варианта

## Первый варик

Продолжаем жертвовать временем первоначальной загрузки

### Плюсы

- Кэшируются все запросы на вп, сильно уменьшается нагрузка на сеть
- Меньше нагрузка на устройство клиента

### Минусы

- Заметно влияет на время первоначальной загрузки
- Увеличивается размер приходящего html

## Второй варик

Переносим работу с запросами на client side

### Плюсы

- Никак не влияет на первоначальную загрузку

### Минусы

- Сильнее нагружается устройство клиента
- Нет кэширования запросов
- Увеличивается нагрузка на сеть

## Но это всё в прошлом (вроде как)

Раз уж недавно анонсировали новый некст - можем попробовать использовать [streaming ssr](https://nextjs.org/docs/advanced-features/react-18/streaming), это "два стула", для нас вообще идеальное решение

@carminio посмотри, встанет ли последний некст на наш стек сейчас, если нет - тогда в ближайшее время подготовлю тулзы для миграции, так как фича очень полезная

**Comment by carminio** [comment]
@TFK70 

1. Обновил некст до 13 версии и реакт до 18

2. Отсюда появился typecheck, видимо 13й некст не совсем на стек встал
<details>

```js
➤ YN0000: │   Error: Cannot find name 'Awaited'.
➤ YN0000: │ 
➤ YN0000: │   200 | ) => Promise<GetServerSidePropsResult<P>>
➤ YN0000: │   201 |
➤ YN0000: │ > 202 | export type InferGetServerSidePropsType<T extends (args: any) => any> = Awaited<
➤ YN0000: │       |                                                                        ^
➤ YN0000: │   203 |   Extract<Awaited<ReturnType<T>>, { props: any }>['props']
➤ YN0000: │   204 | >
➤ YN0000: │   205 |

```

</details>

4. Для того чтобы реализовать streaming ssr, нужен [каталог app](https://nextjs.org/docs/advanced-features/react-18/streaming), [сделал](https://github.com/torin-asakura/shdvor/tree/fix/bugs/site/app/app), но они изменили подход, теперь нет папки pages, все просто в одной куче, вот их [пример](https://github.com/vercel/app-playground/tree/main/app) 

5. Для SSR теперь делают [так](https://github.com/vercel/app-playground/blob/main/app/ssr/%5Bid%5D/page.tsx), больше нет get-server-side-props, просто делают [функцию](https://github.com/vercel/app-playground/blob/main/app/ssr/%5Bid%5D/page.tsx#L1), делают компонент Page [асинхронным](https://github.com/vercel/app-playground/blob/main/app/ssr/%5Bid%5D/page.tsx#L10) и внутри него вызывают с помощью await функцию с данными, то есть не как раньше через пропсы. [Попробовал](https://github.com/torin-asakura/shdvor/blob/fix/bugs/site/pages/index-page/src/index.page.tsx) сделать что-то похожее, не работает

**Comment by Nelfimov** [comment]
@oksssvv начинаем оптимизацию:
- грейдим фронт до последних версий
- берем новый бандл
- проверяем работоспособность
- переводим на `app router`

далее делаем как в драмине и дт с поправкой на `app router`:
- серверные компоненты
- статичные страницы (без `dynamic`)

**Comment by oksssvv** [comment]
что сделано:
- пропатчены: react, react-dom, react-int, styles deps, apollo & gql
- удалены некоторые неиспользуемые пакеты
- подвинуты в дев пакеты для разработки
- убрала некоторые resolutions

что осталось (подготовка):
- разобраться с местом нахождения atls бандла (там рефактор репы идет как поняла), поставить
- прогрейдить typescript & types/ react & react-dom & node
- в планах полностью избавиться от resolutions

**Comment by Nelfimov** [comment]
Решено:
- перешли на nextjs 14
- подключили ssr
- подключили isr
