### ISSUE TITLE
Prices debugging

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shdvor#42]
## Ошибка

```shell
{"level":30,"severity":"INFO","logName":"Bootstrap","timestamp":1671097134723,"textPayload":"initializing"}
{"level":30,"severity":"INFO","logName":"Fetch-data","timestamp":1671097135039,"textPayload":"successful fetching: https://api.aqsi.ru/pub/v2/Goods/list"}
{"level":50,"severity":"ERROR","logName":"Fetch-data","timestamp":1671097135051,"message":"Unexpected end of JSON input SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at Response.json (/workspace/dist/index.js:48311:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async fetchData (/workspace/dist/index.js:213:16)\n    at async bootstrap (/workspace/dist/index.js:23:27)","serviceContext":{"service":"prices"}}
{"level":30,"severity":"INFO","logName":"Fetch-data","timestamp":1671097135269,"textPayload":"successful fetching: https://api.aqsi.ru/pub/v2/GoodsCategory/list"}
{"level":50,"severity":"ERROR","logName":"Fetch-data","timestamp":1671097135269,"message":"Unexpected end of JSON input SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at Response.json (/workspace/dist/index.js:48311:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async fetchData (/workspace/dist/index.js:213:16)\n    at async bootstrap (/workspace/dist/index.js:24:35)","serviceContext":{"service":"prices"}}
/workspace/dist/index.js:27
    const queryPromises = [...Array(jsonGoodsData.pages)].map(async (_, index) => (0, http_4.fetchData)(`${http_1.API_URL}${http_3.GOODS_LIST_PATH}?pageNumber=${index}`));
                                                  ^

TypeError: Cannot read properties of null (reading 'pages')
    at bootstrap (/workspace/dist/index.js:27:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Энв

`API_URL:       https://api.aqsi.ru/pub/v2`
`...креды от бакета в клауде`

**Comment by carminio** [comment]
@TFK70 у тебя и локально такая ошибка? Или это и есть локально

**Comment by TFK70** [comment]
@carminio не знаю, я локально ничего не запускал
Для более правдивых тестов нужно запускать в докере

**Comment by carminio** [comment]
@TFK70 не совсем понял как мне эту ошибку получить, если всё фетчится + файл генерится?

**Comment by TFK70** [comment]
@carminio скажи просто из-за чего ошибка может быть, это твй код ведь

**Comment by carminio** [comment]
> @carminio скажи просто из-за чего ошибка может быть, это твй код ведь

Начнём с малого, попробуй у себя запустить через докер этот сервис, но перед началом нужно внести изменения в двух файлах:

в [bootstrap.ts](https://github.com/torin-asakura/shdvor/blob/master/prices/service-entrypoint/src/bootstrap.ts#L53) 
заменить на - `const task = cron.schedule('*/3 * * * * *', () => {`

в [generate-xml.ts](https://github.com/torin-asakura/shdvor/blob/master/prices/service-entrypoint/src/generator/generate-xml.ts#L79-L90)

Закомменти upload, и добавить рядом -
```ts
writeFile(`./prices/service-entrypoint/src/result/prices-${new Date().toISOString()}.xml`, xml, (err) => {
    if (err) throw err
  })
```

После чего запусти сервис и скажи генерится файл или нет.

Просто я не могу дебажить то, не знаю что, как дебажить ошибку который нет? Я не отрицаю её существования, но у меня её нет :( , отсюда что я могу сказать из-за чего она появляется или того хуже отдебажить её? Это получается мне нужно внести правки в код на веру что поможет, ибо по факту я не могу быть уверен что правки помогли. 🤔

На данном этапе могу  лишь только предположить, что при фетче данных по индексу страницы (ошибка которая указана в логе), не дожидается этой [даты](https://github.com/torin-asakura/shdvor/blob/master/prices/service-entrypoint/src/bootstrap.ts#L19) и начинает работу до того, как придут данные из `jsonGoodsData`. Просто от этого предположения ни горячо, ни холодно, ибо отдебажить не выйдет, так как в конечном счёте не узнаешь сработало оно или нет

**Comment by TorinAsakura** [comment]
@Nelfimov ты даже переоткрыл её в феврале

**Comment by Nelfimov** [comment]
Эта ошибка уже пофикшена новым ключом

![image](https://github.com/torin-asakura/shdvor/assets/44067768/93eb3b29-9126-488a-a1a2-6932551ffe48)
