### ISSUE TITLE
Бамп версий `blog`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#53]
### С чем связан запрос на фичу?

Необходимо прогрейдить версии у `blog` до последних актуальных.

### С чем связан запрос на фичу?

Необходимо прогрейдить версии у `app` до последних актуальных.

### Расскажите как вы это себе видите

- [x] бамп версий в `app`
- [x] переход в NextJS с `pages` на `app` роутер

> [!IMPORTANT]
>
> Если есть пакет который используется в `blog` и в `prices` - не трогаем
> Если есть пакет который используется в `blog` и в `app` - трогаем

- [ ] проверить функционал и верстку со стейджем - https://blog.shdvor.pro

**Comment by effektivnayarabota1** [comment]
- типы по всему приложению
- рефактор одного большого фрагмента, разбил на более мелкие, разнес хуки, поправил верстку (страница с картой)
- добавил `revalidate` для страниц. в `pages` роутере выставляли заголовки ответов (сейчас такой возможности нет),  поставил [вот это](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#revalidate)
- `react-helmet` не получилось поместить в `рутовый layout` - была ошибка, на страницах работает
- разносил хуки в компонентах, немного рефакторил
- была мелочевка по всему приложению разбросанна, её подчистил
- нужно запустить чеки, посмотреть, уточнить типы
- есть функционал, который я закомментил, т.к. не нашел его использования в приложении. - ошибок при запуске не было

не понимаю, почему мы верстаем в наших проектах с промежуточными боксами, вместо `паддингов` и `гэпов`

**Comment by effektivnayarabota1** [comment]
@Nelfimov ^^^

**Comment by Nelfimov** [comment]
> не понимаю, почему мы верстаем в наших проектах с промежуточными боксами, вместо `паддингов` и `гэпов`

https://ishadeed.com/article/building-real-life-components/

**Comment by Nelfimov** [comment]
![Screenshot 2024-08-28 at 14 50 35](https://github.com/user-attachments/assets/2c571314-f5d4-42cf-9672-51539aafdd08)

Надо пересмотреть зависимости в package.json - в проде не запускается
