### ISSUE TITLE
Управление версиями `yarnrc`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#57]
### С чем связан запрос на фичу?

Изменить конфигурацию `yarnrc` для фиксации версий.

### Расскажите как вы это себе видите

Добавить `defaultSemverRangePrefix ` и `preferReuse `

Примеры:

https://github.com/atls-lab/template/blob/aaba9d2347bac6d691f79304b4d191f76347b4cf/.yarnrc.yml#L3
https://github.com/atls-lab/template/blob/aaba9d2347bac6d691f79304b4d191f76347b4cf/.yarnrc.yml#L7

**Comment by effektivnayarabota1** [comment]
@Nelfimov таску закрыли

**Comment by Nelfimov** [comment]
ты можешь самостоятельно закрывать задачи после мержа либо писать в ПРе `closes {ссылка на таску}`

**Comment by effektivnayarabota1** [comment]
@Nelfimov вот при создании ПР забыл добавить `closes`, а в интерфейсе не нашел кнопку

**Comment by Nelfimov** [comment]
прикрепить в сайдбаре задачу
