### ISSUE TITLE
добавление `types` для `queries`

### ISSUE THREAD

**Issue by effektivnayarabota1** [torin-asakura/shdvor#59]
### Какого рода задача?

добавить типы по скачанной схеме

### Что и где будем менять?

используя `graphql-codegen` добавить типы для `queries`, скачали `scheme` в `root`. 
`queries` находятся в `@globals/data`

### Укажите референс

https://github.com/atls/team-management

**Comment by effektivnayarabota1** [comment]
@Nelfimov `схема` должна нахдиться в `руте`, или её лучше поместить рядом с `кодгеном`?

**Comment by Nelfimov** [comment]
@effektivnayarabota1 на твое смотрение. Если она глобальная для всего приложения, имеет смысл  держать в глобале
