### ISSUE TITLE
SSR для `site`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#66]
### С чем связан запрос на фичу?

Необходимо сделать запросы к graphql на сервер, а данные на клиент передавать в кэше. Так страница к клиенту будет приходить уже полностью готовая и мы сможем дальше оптимизировать приложение.

### Расскажите как вы это себе видите

[Теория](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering) 

- [x] переделать создание `apollo client` на использование SSR
- [x] продублировать запросы с клиента на страницы в сервере
- [x] особое внимание на `use client`

### Приложите пример реализаций

https://github.com/candify-tech/web/tree/master/globals/data - конкретный пакет в проекте, в котором реализовали `apollo client` для SSR с апп роутером. Можно так же оценить весь репозиторий как оформляются запросы

**Comment by effektivnayarabota1** [comment]
> https://github.com/candify-tech/web/tree/master/globals/data - конкретный пакет в проекте, в котором реализовали `apollo client` для SSR с апп роутером. Можно так же оценить весь репозиторий как оформляются запросы

![image](https://github.com/user-attachments/assets/27da62bd-1841-4592-a791-5fda7c76f950)

**Comment by Nelfimov** [comment]
В помощь для работы с аполло и кэшем - https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm?pli=1

**Comment by effektivnayarabota1** [comment]
> В помощь для работы с аполло и кэшем - https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm?pli=1

несколько клиентов - так и должно быть?
![image](https://github.com/user-attachments/assets/3ea81a15-67e7-455c-8947-495e1d500f30)

**Comment by Nelfimov** [comment]
> > В помощь для работы с аполло и кэшем - https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm?pli=1
> 
> несколько клиентов - так и должно быть? ![image](https://private-user-images.githubusercontent.com/70315473/362732471-3ea81a15-67e7-455c-8947-495e1d500f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDM5MzcsIm5iZiI6MTcyNDk0MzYzNywicGF0aCI6Ii83MDMxNTQ3My8zNjI3MzI0NzEtM2VhODFhMTUtNjdlNy00NTVjLTg5NDctNDk1ZTFkNTAwZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE1MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjhlMDIwNTkwZWUwMGIyNGY1NjE1M2I3NTQ5YjIyN2IxYjRlODJhMDdkNjUzNmI4MTgxZDRmOWZiZjI2YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnCi1awPq6ncwzxYNPrdD531kXaq4bqDNuUKnlX4Vdw)

Да

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- разбирался в документации
- переписал клиентский аполло
- написал серверный аполло
- не тестировал
#### Дальнейшие планы
- протестировать текущие версии клиентов
- убедиться в корректной работе
- переписать все страницы
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- переписал `getter-функции` для использования с серверным аполло
- переписал провайдеры, вынес их в отдельный клиентский компонент
- разбирался с ошибкой - `useSuspenseQuery` в клиентском комопненте. проблему не решил
  - выглядит так, какбудто эта функция вызывается не на той стороне приложения
  - проверил `wrapper` - все ок
  - директиву `'use client'` - использую на том же уровне
  - можем быть ошибка в конфиге, пересмотрю
  - в остальном, код взял из кендифай
```ts
Attempted import error: 'registerApolloClient' is not exported from '@apollo/experimental-nextjs-app-support' (imported as 'registerApolloClient').
```
#### Дальнейшие планы
- решить ошибку
- провести все запросы ко всем страницам
- клиентские запросы
- опустить директиву `'use client'` как можно ниже, вместе с клиентскими запросами
#### Актуальная ветка
https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr

**Comment by Nelfimov** [comment]
> ```ts
> Attempted import error: 'registerApolloClient' is not exported from '@apollo/experimental-nextjs-app-support' (imported as 'registerApolloClient').
> ```

Ошибка точно связана со средой исполнения кода - сервер или клиент. Проверь досконально всю цепочку - кто вызывает функцию и где используется.

**Comment by effektivnayarabota1** [comment]
> Это твое локальное. Вот мой стейдж:
> 
> ![image](https://private-user-images.githubusercontent.com/44067768/364000529-f10f6e88-ad41-4471-a2f0-5bf970bb9b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzA1OTAsIm5iZiI6MTcyNTM3MDI5MCwicGF0aCI6Ii80NDA2Nzc2OC8zNjQwMDA1MjktZjEwZjZlODgtYWQ0MS00NDcxLWEyZjAtNWJmOTcwYmI5YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEzMzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NzExMzBiMjgzNTY2ODBiYTQ3MzZkNDAzN2QyNmVmNzFlN2RhNmQyODU5MTk0MDc1ZjQwM2YxZTI3YzM0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g_poEsle0OTq-AN-qmjiG7UTy078-Tvtdoowp0JLsIk)

- а меня `вордпресс` не мог в блок кинуть изза количества запросов?
- именно с `wp.shdvor.pro` не доходит
- с впн зашел, работает

**Comment by Nelfimov** [comment]
@effektivnayarabota1 не должен - проверил настройки, там ничего такого нет.

Можешь протестировать драмин - там тоже вордпресс.

**Comment by effektivnayarabota1** [comment]
> Можешь протестировать драмин - там тоже вордпресс.

тоже самое

**Comment by effektivnayarabota1** [comment]
> @effektivnayarabota1 не должен - проверил настройки, там ничего такого нет.
> 
> Можешь протестировать драмин - там тоже вордпресс.

заработало

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- решил вчерашнюю ошибку
- переписал все страницы на `apollo-ssr`:
  - продублировал запросы на клиенте
  - немного поменял пропсы сервер-клиент
  - проверил верстку - все ок
- дурацкая ошибка с вордпресс. новые запросы, кстати, получилось делать ровно через час. все-таки думаю что чтото с самом ворпрессом, есть какието лимиты
#### Дальнейшие планы
- еще раз проверить приходящие данные
- посмотреть, можно ли опустить директиву `use client` на уровень фрагментов.
  - сейчас сделанно также как и было. `use client` на **клиентской стороне `page`**
  - получение `seoData` оставил на сервере, на клиент передаем пропсом. этот компонент не должен быть на клиенте, пересмотрю его завтра
#### Актуальная ветка
https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- вынес `seo.component` в `@ui`
  - этот компонент оставил на клиенте, т.к. `Helmet` использует клиентские хуки
    - можно поменять его на родной некстовский https://nextjs.org/docs/app/api-reference/functions/generate-metadata, @Nelfimov, что скажешь?
- закрыл ошибки типов
  - обновил маршруты для старых типов
  - новые не прописывал, сделал `expect-error`
- повылазили ошибки типов на `@blog`, его тоже переписал под `apollo-ssr`
- запросы на уровень фрагментов опускать не стал. в страницах инициизируются клиентские хуки и они пробрасываются ниже (если нужно это сделать, то лучше в отдельной таске)
  - если опускать запросы на уровень фрагментов, то получится, что мы будем дублировать идентичные запросы у каждого фрагмента, при этом клиентскую часть верстки мы не сильно уменьшим. @Nelfimov подскажи на что ориентироваться в распределении запросов
- решил ошибку аполло с индексацией кэшированных запросов
  - `apollo` жаловался на то, что по идентичному `__typename` - у нас сохраняется несоклько запросов в кэше. добавил в конфиг (на сервере) такую конструкцию:

<details>
<summary>log</summary>

```ts
      cache: new InMemoryCache({
        dataIdFromObject(responseObject) {
          switch (responseObject.__typename) {
            case 'Post':
              console.log(responseObject)
              if (responseObject.seo) {
                return `PostBy:${responseObject.seo.title}`
              } else if (responseObject.postId) {
                return `PostBy:${responseObject.postId}`
              } else if (responseObject.uri) {
                return `PostBy:${responseObject.uri}`
              } else {
                return defaultDataIdFromObject(responseObject)
              }
            case 'Service':
              return `ServiceBy:${responseObject.uri}`
            default:
              return defaultDataIdFromObject(responseObject)
          }
        },
      }),
```

</details>

#### Дальнейшие планы
- обнаружил ошибку при переходе между некоторыми страницами.
  - например между `@blog/index-page` и `@blog/post-page`
  - ошибка содержится в этой функциии - ` const { posts } = getBlogPostsData()`, причина мне покачто неизвестна

- устранить ошибку
- проверить `prepack` у `@site` и `@blog`
- проверить `start` у `@site` и `@blog`
- отправить на ревью

#### Актуальная ветка
https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- решил вчерашнюю ошибку
- почистил код
- проверил сборку и запуск билда у обоих пакетов
- перекрыл `expect-error` - там, где не прописанны типы. те, что были - провел
- отправил на ревью

#### Дальнейшие планы
- жду результаты ревью
- https://github.com/torin-asakura/shdvor/issues/67

#### Актуальная ветка
https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
таску создам под этот баг и двигаюсь дальше?
![image](https://github.com/user-attachments/assets/8f07ea8b-9873-4872-beea-1b9812f72b38)

**Comment by Nelfimov** [comment]
Да. Вот сама ошибка:

![image](https://github.com/user-attachments/assets/f3265d2b-1ad1-4489-a0bd-760c3d38fd21)
