### ISSUE TITLE
Перевести `prices` на ESM

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#68]
### С чем связан запрос на фичу?

Необходимо модернизировать `prices` используя ESM

### Расскажите как вы это себе видите

- [x] переделать на ESM
- [x] проверить хвосты из CJS (__dirname и проч)

**Comment by effektivnayarabota1** [comment]
@Nelfimov 
#### Текущий статус
- занимался этой задачей, все переписал, осталось только проверить. В `ПР` написал, что необходимо
- читал про `ssr`, изучил `candify`, `apollo devtools`, изучал документацию по `apollo-nextjs`
- начал расчерчивать окружение для apollo-ssr 
#### Дальнейшие планы
- получить ключ, о котором пишу в `ПР` -> закончить проверку -> отправить на ревью
- продолжить настройку `apollo-ssr`
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/refactor/prices-esm
- https://github.com/torin-asakura/shdvor/tree/refactor/site-ssr
