### ISSUE TITLE
Обновить `aws-sdk` в `prices`

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#72]
### С чем связан запрос на фичу?

Необходимо обновить `aws-sdk` до последней версии и проверить код.

### Расскажите как вы это себе видите

Библиотека, которую мы используем для работы с бакетом, необходимо обновить:

```
(node:10) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.
```

### Приложите пример реализаций

https://github.com/candify-tech/web/tree/master/applicant/server/adapters/storage-adapter

**Comment by effektivnayarabota1** [comment]
> бакетом

что такое бакет?

> (node:10) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
> on September 8, 2024 and reach end-of-support on September 8, 2025.

эта ошибка из стейджа? я могу до туда достучаться?

**Comment by Nelfimov** [comment]
> > бакетом
> 
> что такое бакет?

Это просто хранилище файлов в облаке.

> > (node:10) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
> > on September 8, 2024 and reach end-of-support on September 8, 2025.
> 
> эта ошибка из стейджа? я могу до туда достучаться?

Со стейджа. Достучаться не можешь - это просто вывод в логи.

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- читал доки
- переписывал на новую версию

#### Дальнейшие планы
- если `aws` сам цепляет переменные окружения и авторизирует клиент, то все готово - @Nelfimov подскажи пожалуйста, как работает
- покачто переменные авторизации закомментировал, т.к. в новом клиенте нет таких параметров:
```ts
  const s3Client = new S3Client({
    endpoint: process.env.FILES_STORAGE_HOST,
    region: process.env.FILES_STORAGE_REGION,
    // accessKeyId: process.env.YC_SA_KEY_ID,
    // secretAccessKey: process.env.YC_SA_SECRET_KEY,
  })
```

#### Актуальная ветка
https://github.com/torin-asakura/shdvor/tree/refactor/update-aws-sdk

**Comment by Nelfimov** [comment]
> #### Дальнейшие планы
> * если `aws` сам цепляет переменные окружения и авторизирует клиент, то все готово - @Nelfimov подскажи пожалуйста, как работает

Цепляет сам - авторизация по переменным окружения, которые есть в стейдже.

> * покачто переменные авторизации закомментировал, т.к. в новом клиенте нет таких параметров:
> 
> ```ts
>   const s3Client = new S3Client({
>     endpoint: process.env.FILES_STORAGE_HOST,
>     region: process.env.FILES_STORAGE_REGION,
>     // accessKeyId: process.env.YC_SA_KEY_ID,
>     // secretAccessKey: process.env.YC_SA_SECRET_KEY,
>   })
> ```

Посмотри пример который я приложил в таску - там как раз все что нужно для авторизации. Для примера: последняя работа с бакетом яндекса: https://github.com/atls/serverless-yandex/tree/master/adapters/storage

**Comment by Nelfimov** [comment]
Стейдж

```
{"level":50,"name":"XML-Generator","body":{"code":"ERR_INVALID_URL","input":"storage.yandexcloud.net"},"severityNumber":17,"severityText":"ERROR","timestamp":1725956462874}
```

**Comment by effektivnayarabota1** [comment]
> storage.yandexcloud.net

а вот это значение у нас вот в эту переменную окружения пишется, верно?

```ts
    endpoint: process.env.FILES_STORAGE_HOST,
```

**Comment by Nelfimov** [comment]
![image](https://github.com/user-attachments/assets/e3c01e8f-aa0b-41f2-87c4-a52d37066bf1)

**Comment by Nelfimov** [comment]
@effektivnayarabota1 поменял в стейдже. Посмотрим как пойдет. Пока закрываю
