### ISSUE TITLE
Переход по лого

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#75]
### Описание бага

Не работает переход по логотипу

### Воспроизведение

1. Клик по логотипу

### Ожидаемое поведение

Переход на индекс

### Материалы

https://github.com/user-attachments/assets/e582cb98-fd8e-455d-9e06-5815c2bad3a7

### Данные окружения

Chrome 128.0.6613.120

**Comment by effektivnayarabota1** [comment]
- внутри`@site`:
  - услуги - лого
  - страница услуги - лого
  - контакты - лого
 - работает корректно
---
- внутри `@blog`
  - страница поста - лого
- работает, перенаправляет на домашнюю странцу `@blog`
- @Nelfimov будем менять перенаправление на домашнюю странцу `@site`? - как будто так будет логичнее
---
- при возвращении с `@blog` на `@site`
 - перестает рабоать переход по лого c любой страницы
 - чтобы восстановить работу нужно открыть сайт в новой вкладке
 - обновление страницы не помогает
 - выключение кэша не помогает

**Comment by Nelfimov** [comment]
> * @Nelfimov будем менять перенаправление на домашнюю странцу `@site`? - как будто так будет логичнее

да
