### ISSUE TITLE
Баги адаптивности

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#79]
### Описание бага

Есть UI баги адаптивности для некоторых элементов страницы. Напр., карточки записей блога.

### Воспроизведение

1. https://shdvor.pro
2. меняем ширину экрана

### Ожидаемое поведение

Адаптивность работает

### Материалы

https://github.com/user-attachments/assets/1e9a075c-a59c-47e7-a32c-c0f18170dcde

### Данные окружения

Safari Version 17.6 (19618.3.11.11.5)

**Comment by effektivnayarabota1** [comment]
#### Текущий статус
- начал править верстку
- хочу вынести фиксированные размеры внаружу каточек, детям дать 100%.
- поправил разрешение 768, мобильное уехало
#### Дальнейшие планы
- поправить мобильное разрешение
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/fix/layout
