### ISSUE TITLE
Управление ценами

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/shdvor#9]
## Проблема

Инконсистентность цен в акси и яндекс бизнесе

## Задача

- [x] Брать цены с акси, результат сгенерить в JSON
- [x] Из JSON сгенерить YML для яндекс бизнеса
- [x] Выгрузить результат в яндекс бизнес и в WP
- [x] Изменения на стороне акси происходят редко, так что проводить синхронизацию достаточно раз в неделю (cron)

## Стек

- Сервис должен запускаться из-под `yarn service` (из тулзов)
- Typescript

## Материалы
[Справка Яндекса](https://yandex.ru/support/business-priority/manage/price-list.html#price-list__yml-file)

**Comment by TFK70** [comment]
**Конечный формат файла:** xml (ICML) ([примеры](https://yandex.ru/support/marketplace/assortment/files/index.html))

### Сопоставление форматов

**Начало:**

Все находится внутри свойства `<shop>`.

Список константных значений:

```xml
<shop>
   <name>BestSeller</name>
   <company>Tne Best inc.</company>
   <url>http://best.seller.ru</url>
   <platform>uCoz</platform>
   <version>1.0</version>
   <agency>Технологичные решения</agency>
   <email>example-email@gmail.com</email>
   .....
</shop>
```

**Позиция:**

Все данные указываются внутри свойства `<offer>`:

```xml
<offer>
....
</offer>
```

**Категория:** 

Все возможные категории указываются в отдельной секции `<categories>`

В id может быть указано любое число (можно просто указывать там индекс 0,1,2,3 и тд)

```xml
<categories>
   <category id="1">Название</category>
</categories>
```

Чтобы указать принадлежность товара к категории:

(далее `<offer>` как родительская категория указываться не будет, для удобства, но она подразумевается)
```xml
<offer>
   <categoryId>101</categoryId>
</offer>
```

**Название:**

`<name>Название</name>`

**Описание:**

`<description>Описание</description>`

**Цена:**

```xml
```

**Comment by TFK70** [comment]
@TorinAsakura напоминалка про использование AQSI как точку входа

**Comment by carminio** [comment]
### План
1. Сделать окружение
2. Получать с api aqsi цены услуг
3. Сохранить их в json

**Comment by TFK70** [comment]
> @TFK70
> 
> > Изменения на стороне акси происходят редко, так что проводить синхронизацию достаточно раз в неделю (cron)
> 
> Поподробнее, как реализовать?

Сначала почитай про cron, потом береш [это](https://github.com/node-cron/node-cron), выставляешь джоб на "раз в неделю" (`0 0 * * 0`) и всё, твой кусок кода исполняется раз в неделю

**Comment by TFK70** [comment]
@carminio выгружать товары нужно на яндекс услуги, яндекс бизнес будет брать все услуги оттуда

**Comment by TFK70** [comment]
@carminio итоговый файл нужно выгружать в бакет

Так как в конечном итоге Андрею нужно будет ходить за ним руками - тебе нужно выгружать его в облачное хранилище файлов, это и есть бакет. Он базируется в нашем яндекс облаке, я дам тебе от него креды, во время локальной разработки просто дёргай меня, чтобы я проверил загрузился файл или нет

Для работы с бакетом используй либу `aws-sdk`, вот пример инициализации:

```javascript
const s3 = new AWS.S3({
      endpoint: process.env.FILES_STORAGE_HOST,
      region: process.env.FILES_STORAGE_REGION,
      accessKeyId: process.env.YC_SA_KEY_ID,
      secretAccessKey: process.env.YC_SA_SECRET_KEY,
    })
```

Все эти энв переменные я тебе и предоставлю

**Comment by TorinAsakura** [comment]
Джоба работала, всё было в порядке, мы с тобой уже проводили анализ пода в котором она запущена, там что-то с окружением было

**Comment by Nelfimov** [comment]
@TorinAsakura файл генерируется успешно, заливается в бакет.

Необходимо вручную https://yandex.ru/support/business-priority/manage/price-list.html#price-list__yml-file либо через API (если есть, тут нет - https://yandex.ru/dev/business-api/doc/ref/index.html) загрузить новые данные.

**Comment by TorinAsakura** [comment]
> @TorinAsakura файл генерируется успешно, заливается в бакет.
> 
> Необходимо вручную https://yandex.ru/support/business-priority/manage/price-list.html#price-list__yml-file либо через API (если есть, тут нет - https://yandex.ru/dev/business-api/doc/ref/index.html) загрузить новые данные.

![Снимок экрана 2024-05-22 в 14 05 31](https://github.com/torin-asakura/shdvor/assets/3940885/d4b5c3ea-c877-4d61-82b0-f54784253fc5) - можем паблить yml-фид

**Comment by Nelfimov** [comment]
тогда можно создавать дополнительно отдельный файл, напр. `prices-latest`, его выкладывать в CDN и залить ссылку на него в фид.

ок?

**Comment by TorinAsakura** [comment]
> тогда можно создавать дополнительно отдельный файл, напр. `prices-latest`, его выкладывать в CDN и залить ссылку на него в фид.
> 
> ок?

именно так и нужно делать, правда не знаю насколько оправдано брать целый CDN под один фид, если это будет не дорого/бесплатно - ок, если же CDN будет потреблять больше условных 100₽/месяц - значит надо выгружать это текущий хостинг через экшен или настроить ACL для текущего бакета чтобы прайс был публичным

**Comment by Nelfimov** [comment]
Открыл доступ к бакету через ACL - сделать публичным один файл не вышло. 

Файл будет перезаписываться каждую неделю - поставил напоминание через неделю на проверку.

https://storage.yandexcloud.net/shdvor/prices-latest.xml

**Comment by TorinAsakura** [comment]
> Открыл доступ к бакету через ACL - сделать публичным один файл не вышло.
> 
> Файл будет перезаписываться каждую неделю - поставил напоминание через неделю на проверку.
> 
> https://storage.yandexcloud.net/shdvor/prices-latest.xml

Проверю в 01:17 по МСК

**Comment by Nelfimov** [comment]
> Файл будет перезаписываться каждую неделю - поставил напоминание через неделю на проверку.
> 
> https://storage.yandexcloud.net/shdvor/prices-latest.xml

Файл перезаписался - интеграция с яндекс бизнесом идет успешно. Следующий раз надо будет перепроверить когда обновим цены в акси.

Таску закрываю.
