### ISSUE TITLE
Google AMP

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/shdvor#98]
### С чем связан запрос на фичу?

Необходимо изучить и добавить Google AMP в `site` и `blog`

### Расскажите как вы это себе видите

- [ ] изучить https://developers.google.com/amp
- [ ] внедрить в наши энтрипоинты

**Comment by kirill-ivanovvv** [comment]
@Nelfimov 
- у AMP есть playground, в котором мы можем протестировать - подходит ли наша верстка по требованиями
- вот такой результат у меня получился, когда я подставил верстку страницы сайта:
![image](https://github.com/user-attachments/assets/876ed1c2-75cd-41e5-8aae-817cf4b618b6)
![image](https://github.com/user-attachments/assets/6b1ef186-d5c6-454f-af08-33f877b916c5)
- мне кажется легче будет сверстать страницы с нуля на шаблонизаторе, оставив только тот контент, который нужен - текстовые абзацы, изображения, цены, и контакты, header и footer.
  - в документации AMP не вижу пункта про то, что контент должен повторяться. у yandex-turbo - было
  - в yandex-turbo я просто забрасываю нашу странцу без изменений. проверить корретность верстки не могу, тк такого же playground, как в AMP - нет. информацию про различия в тегах я там не видел, поэтому рассчитываю на работоспособность
- тут требований больше и они другие, че у yandex-turbo, но принцип похож
  - нужно будет заменить ссылки на внешние ресурсы, например изображения. со стандартных страниц мы делаем относительный запрос типа `/_next/image?image-source.png`. в шаблонах нужно будет запрашивать изображения напрямую с WP либо добавить в путь site-origin
  - по-другому стилизуются контейнеры
  - стили полностью отвалились. я бы подключил какую-нибудь библиотеку, подбил минимальную стилизацию

**Comment by Nelfimov** [comment]
> * мне кажется легче будет сверстать страницы с нуля на шаблонизаторе, оставив только тот контент, который нужен - текстовые абзацы, изображения, цены, и контакты, header и footer.

Это будет отдельная страница или нужно текущую редактировать?

>   * нужно будет заменить ссылки на внешние ресурсы, например изображения. со стандартных страниц мы делаем относительный запрос типа `/_next/image?image-source.png`. в шаблонах нужно будет запрашивать изображения напрямую с WP либо добавить в путь site-origin

Картинки можно вынести в CDN либо WP. Главное собери список какие.

>   * по-другому стилизуются контейнеры
>   * стили полностью отвалились. я бы подключил какую-нибудь библиотеку, подбил минимальную стилизацию

Стилизация хромает потому что мы используем CSS in JS, который выполняется в рантайме. С этим ничего не сделать кроме как переходить на новый `hyperion`. Однако это долго.

Поэтому тут все зависит от ответа на 

> Это будет отдельная страница или нужно текущую редактировать?

**Comment by kirill-ivanovvv** [comment]
> Это будет отдельная страница или нужно текущую редактировать?
> 
> >

удобнее сделать отдельные. для каждой страницы своя amp-версия

**Comment by Nelfimov** [comment]
в таком случае можешь делать отдельный `ui`, в который возьмешь компоненты из нового `hyperion`. С помощью них сделаешь страницу.

Так же тебе нужен будет генератор https://github.com/atls/figma

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- изучал документацию
- начал делать альтернативный layout для amp-страниц
#### Дальнейшие планы
- закончить лейаут
- создать дополнительный ui-слой для apm-компонентов
- переверстать страницы
#### Актуальная ветка
- ошибки на чеках, не могу запушить

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- занимался yandex-turbo
- по текущей задаче - псевдо-верстка + проверял как делать лейаут. по всей видимости придется делать роутинг не через pages, а через api-роуты и html-респонсы. next коверкает верстку и выдергивает из тэга head основной атрибут для amp-страниц - `amp`
#### Дальнейшие планы
- дальнейшая детализация страниц, верстка компонентов
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/google-amp
- сырой код, не могу залить

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- написал геттеры, которые возвращают верстку страницы в строке. будем отправлять через гет-роут.
- начал рефактор и исправлять ошибки тайпчектов, переключился на дельту
#### Дальнейшие планы
- закоммититься
- вернуться к верстке
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/google-amp
- код не обновлял

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- рефакторинг
- ошибки при чеке
- начал добавлять обновленный гиперион. покачто только для google-amp компонентов, кое что не сходится

#### Дальнейшие планы
- тк я хотел отправлять на клиент html-строку в ответ на гет-запрос через route.ts - у меня не загружаются стили. в компоненте все проставляется, но ресурсы на клиент не доходят.
- не понимаю на каком моменте отправляются файлы со стилями, разобраться с этим

- можно попробовать сделать все-таки через pages и обычную jsx-верстку, но у меня не получается пропихнуть в эту верстку [amp-аттрибуты](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-boilerplate.md)
- я отправляю этот код на клиент, а доходит он без `amp-boilerplate`. просто `<style>`
- попробовать сделать это через `dangerouslySetInnerHTML` в `head`

#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/google-amp

**Comment by kirill-ivanovvv** [comment]
@Nelfimov

- не нашел варианта, как встроить в layout.tsx amp-атрибуты. next форматирует их по-своему, нужные нам выдергивает.
- если отправлять на гет-запрос html-строку - то все работает
- vanilla-extract работает только со сборщиком, не могу сообразить как это встроить в решение со строкой
---
- предлагаю собрать простой css-файл и отправлять его тоже по гет-запросу
- скопирую стили шрифтов из оригинального дизайна
- создам несколько стандартных контейнеров-оберток
- отступы зашью в ЦСС-константу
- все остальные +- интерактивные элементы - нужно брать из amp-библиотеки https://amp.dev/documentation/components/
---
- вот в этих 2х функциях я собираю из jsx-верстки html-строку. просто в лейаут добавлю относитьльую ссылку на css-роут
1. https://github.com/torin-asakura/shdvor/blob/feat/google-amp/globals/data/src/getters/jsx-html-string.getter.ts
2. https://github.com/torin-asakura/shdvor/blob/feat/google-amp/globals/data/src/getters/google-amp-page.getter.ts

**Comment by Nelfimov** [comment]
Прежде чем все это претворять в жизнь - распиши с каким кодом проблемы и что пытался сделать. 

Код можешь вставлять ссылками

**Comment by Nelfimov** [comment]
@TorinAsakura АМР больше не в почете - nextjs оставил его поддержку в 12 версии вместе с `page` роутером:

https://nextjs.org/learn-pages-router/seo/rendering-and-ranking/amp

Здесь уже google пишет о "ненужности" его если web vitals хорошие

https://developers.google.com/search/blog/2021/04/more-details-page-experience#details

Ну и просто коммент с реддита

https://www.reddit.com/r/nextjs/comments/1dpuvj7/comment/lam2grg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

---

Если все же делать - то мне видится два пути:
- даунгрейдится на `pages` роутер - быстро, но это тупик - этот роутер в режиме maintanance
- делать доп. энтрипоинт на `pages` роутере - сложнее. Дополнительно обременяем себя поддержкой двух приложений

**Comment by Nelfimov** [comment]
Перевел в статус `await` пока

**Comment by TorinAsakura** [comment]
Пидорский гугл…©
